export type EquipmentKey =
  | 'dumbbells' | 'barbell' | 'cables' | 'machines'
  | 'hammer_strength' | 'kettlebells' | 'bands' | 'bodyweight'

export const EQUIPMENT_LABELS: Record<EquipmentKey, string> = {
  dumbbells:       'Dumbbells',
  barbell:         'Barbell',
  cables:          'Cables',
  machines:        'Machines',
  hammer_strength: 'Hammer Strength',
  kettlebells:     'Kettlebells',
  bands:           'Bands',
  bodyweight:      'Bodyweight',
}

export const EQUIPMENT_ICONS: Record<EquipmentKey, string> = {
  dumbbells:       '🏋️',
  barbell:         '🔩',
  cables:          '🔗',
  machines:        '⚙️',
  hammer_strength: '🔨',
  kettlebells:     '🔔',
  bands:           '🎀',
  bodyweight:      '🤸',
}

export interface Alt { name: string; cue: string }
export type AltsMap = Partial<Record<EquipmentKey, Alt[]>>

// ── Alternatives for every exercise ──────────────────────────────────
export const EXERCISE_ALTS: Record<string, AltsMap> = {

  // ── WORKOUT A ────────────────────────────────────────────────────────
  'Machine Lateral Raise': {
    cables:          [{ name:'Behind-the-Back Cable Lateral Raise', cue:'Cable behind body · constant tension · natural arc' },
                      { name:'Leaning Cable Lateral Raise',         cue:'Lean away from stack · maximises stretched position' }],
    dumbbells:       [{ name:'DB Lateral Raise',                    cue:'3-sec eccentric · slight lean · thumb down at top' },
                      { name:'DB Lateral Raise (Lying)',            cue:'Lie on bench · raise top arm · maximises stretch at bottom' }],
    bands:           [{ name:'Band Lateral Raise',                  cue:'Stand on band · bilateral or unilateral' }],
    kettlebells:     [{ name:'KB Lateral Raise',                    cue:'Same arc as DB — control the eccentric carefully' }],
    bodyweight:      [{ name:'Wall Lateral Raise',                  cue:'Face wall · raise arm along wall · isolates delt' }],
  },

  'Reverse Cable Fly': {
    cables:          [{ name:'Single-Arm Reverse Cable Fly',        cue:'One arm at a time for better contraction focus' }],
    dumbbells:       [{ name:'DB Rear Delt Fly',                    cue:'Hinge forward · lead with elbows · slow 3-sec return' }],
    machines:        [{ name:'Pec Deck Rear Delt (Reverse)',        cue:'Reverse position on pec deck · arms wide · squeeze' }],
    bands:           [{ name:'Band Pull-Apart',                     cue:'Hold band at chest height · pull apart to T · squeeze' }],
    kettlebells:     [{ name:'KB Rear Delt Row',                    cue:'High elbow row · focus on rear delt squeeze not lat pull' }],
    bodyweight:      [{ name:'Prone Y-Raise',                       cue:'Lie face down · raise arms in Y shape · rear delt + lower trap' }],
  },

  'Incline DB Curl': {
    barbell:         [{ name:'EZ-Bar Curl',                         cue:'Slight supination grip · full extension · elbows fixed' }],
    cables:          [{ name:'Cable Curl (High Pulley)',            cue:'Arms up at cable height · curl toward ears · peak contraction' }],
    machines:        [{ name:'Machine Preacher Curl',               cue:'Chest against pad · eliminates cheating · full stretch' }],
    dumbbells:       [{ name:'DB Concentration Curl',              cue:'Elbow on inner thigh · full isolation · no body swing' }],
    bands:           [{ name:'Band Curl',                           cue:'Stand on band · full ROM · squeeze at top' }],
    kettlebells:     [{ name:'KB Curl (Supinating)',                cue:'Neutral to supinated grip through ROM' }],
    bodyweight:      [{ name:'Underhand Inverted Row',              cue:'Supinated grip · curl toward bar — compound bicep work' }],
  },

  'Cable Curl': {
    barbell:         [{ name:'Barbell Curl',                        cue:'Elbows fixed · full extension · supinate at top' }],
    dumbbells:       [{ name:'Alternating DB Curl',                 cue:"Supinate at top · don't swing · slow 3-sec eccentric" }],
    machines:        [{ name:'Machine Curl',                        cue:'Smooth resistance curve · isolate without stabilisation' }],
    bands:           [{ name:'Band Curl',                           cue:'Stand on band · constant tension · slow lowering' }],
    kettlebells:     [{ name:'KB Curl',                             cue:'Neutral or supinating · different bell angles challenge differently' }],
    bodyweight:      [{ name:'Chin-Up',                             cue:'Supinated grip · full dead hang · chin over bar' }],
  },

  'EZ-Bar Skull Crusher': {
    barbell:         [{ name:'Close-Grip Bench Press',              cue:'Hands shoulder-width · lower to chest · tricep-focused press' }],
    dumbbells:       [{ name:'Lying DB Tricep Extension',           cue:'Lie flat · lower DBs to ears · elbows close · press to full lockout' }],
    cables:          [{ name:'Cable Overhead Extension',            cue:'Face away from stack · cable behind head · elbows close' }],
    machines:        [{ name:'Machine Tricep Extension',            cue:'Seated · adjust for full overhead stretch · smooth press' }],
    bands:           [{ name:'Band Skull Crusher',                  cue:'Pin band under head · same arc as EZ-bar version' }],
    kettlebells:     [{ name:'KB Skull Crusher',                    cue:'Hold bell by horns · same movement pattern as EZ-bar' }],
    bodyweight:      [{ name:'Diamond Push-Up',                     cue:'Hands close together · direct tricep loading' }],
  },

  'Cable Overhead Tricep Extension': {
    barbell:         [{ name:'EZ-Bar Overhead Extension',          cue:'Grip inside knurling · elbows close · full stretch overhead' }],
    dumbbells:       [{ name:'DB Overhead Extension (seated)',      cue:'Both hands on one DB · elbows close · full stretch' },
                      { name:'Lying DB Tricep Extension',          cue:'Lie flat · lower DBs toward ears · emphasise stretch' }],
    machines:        [{ name:'Machine Overhead Tricep Extension',   cue:'Adjust seat height · elbows close · full lockout' }],
    bands:           [{ name:'Band Overhead Tricep Extension',      cue:'Stand on band · both hands overhead · press up' }],
    kettlebells:     [{ name:'KB Overhead Extension',              cue:'Hold bell by horns overhead · elbows close · lower behind head' }],
    bodyweight:      [{ name:'Bench Dip',                          cue:'Hands behind on bench · lower slowly · full elbow extension' }],
  },

  'Barbell Bench Press': {
    dumbbells:       [{ name:'Dumbbell Bench Press',        cue:'Full ROM · wrists neutral or pronated · elbows ~45°' },
                      { name:'DB Floor Press',              cue:'Removes bottom stretch — good for shoulder issues' }],
    cables:          [{ name:'Cable Chest Press (seated)',  cue:'Cables active through entire range of motion' }],
    machines:        [{ name:'Chest Press Machine',         cue:'Seat height: handles at lower chest · full extension' }],
    hammer_strength: [{ name:'Hammer Strength Chest Press', cue:'Load both sides evenly · full stretch each rep' }],
    kettlebells:     [{ name:'Kettlebell Floor Press',      cue:'Neutral wrists · press straight up · full lockout' }],
    bands:           [{ name:'Band Push-Up',                cue:'Band across upper back, anchor under palms' }],
    bodyweight:      [{ name:'Push-Up',                     cue:'Chest to floor · elbows track 45° from torso' },
                      { name:'Weighted Push-Up',            cue:'Plate on upper back or vest for added resistance' }],
  },

  'Incline Dumbbell Press': {
    barbell:         [{ name:'Incline Barbell Press',           cue:'30-45° bench · wide grip · bar to upper chest' }],
    cables:          [{ name:'Low-to-High Cable Press',         cue:'Cables set low · press up and together' }],
    machines:        [{ name:'Incline Machine Press',           cue:'Adjust to target upper chest emphasis' }],
    hammer_strength: [{ name:'Hammer Strength Incline Press',   cue:'Drive elbows forward and up at top' }],
    kettlebells:     [{ name:'KB Incline Press',                cue:'Rack bells on forearms · press straight overhead' }],
    bands:           [{ name:'Incline Band Press',              cue:'Anchor band behind bench · press at 45° angle' }],
    bodyweight:      [{ name:'Decline Push-Up',                 cue:'Feet elevated hits upper chest like incline press' }],
  },

  'Cable Chest Fly': {
    dumbbells:       [{ name:'Dumbbell Fly',           cue:'Slight elbow bend · wide arc · feel the stretch' },
                      { name:'DB Incline Fly',         cue:'30° bench · emphasises upper chest' }],
    machines:        [{ name:'Pec Deck Machine',       cue:'Elbows at 90° or arms slightly bent · squeeze at front' }],
    hammer_strength: [{ name:'Hammer Strength Fly',    cue:'Adjust arm pad height to mid-chest' }],
    bands:           [{ name:'Band Fly',                cue:'Anchor band behind you at chest height' }],
    kettlebells:     [{ name:'KB Svend Press / Fly',   cue:'Hold KB between palms · press and flare at top' }],
    bodyweight:      [{ name:'Wide-Grip Push-Up',       cue:'Hands wider than shoulder-width · chest-focused' }],
  },

  'Overhead Press (Barbell)': {
    dumbbells:       [{ name:'Dumbbell Overhead Press', cue:'Neutral or pronated grip · press overhead to full extension' },
                      { name:'Arnold Press',            cue:'Rotate from neutral to pronated as you press — full delt sweep' }],
    cables:          [{ name:'Single-Arm Cable Press',  cue:'Stand sideways to cable · core anti-rotation challenge' }],
    machines:        [{ name:'Machine Shoulder Press',  cue:'Adjust seat so handles start at shoulder height' }],
    hammer_strength: [{ name:'Hammer Strength OHP',     cue:'Full extension overhead · controlled descent' }],
    kettlebells:     [{ name:'KB Overhead Press',       cue:'Rack position · press straight up · lock out bicep by ear' },
                      { name:'KB Push Press',           cue:'Slight dip and drive from legs to assist heavier loads' }],
    bands:           [{ name:'Band Overhead Press',     cue:'Stand on band · press straight up · brace hard' }],
    bodyweight:      [{ name:'Pike Push-Up',            cue:'Hips high, head toward floor · forehead nearly touches ground' }],
  },

  'Behind-the-Back Cable Lateral Raise': {
    dumbbells:       [{ name:'DB Lateral Raise',         cue:'Lead with elbow · slight lean forward · 3-sec eccentric' },
                      { name:'DB Incline Lateral Raise', cue:'Lie sideways on incline bench — removes momentum' }],
    bands:           [{ name:'Band Lateral Raise',       cue:'Anchor band under feet · slow and controlled' }],
    machines:        [{ name:'Machine Lateral Raise',    cue:'Adjust arm pad to forearm — eliminates momentum' }],
    kettlebells:     [{ name:'KB Lateral Raise',         cue:'Keep wrist pronated (thumb down) at top for peak activation' }],
    bodyweight:      [{ name:'Prone Y Raise',            cue:'Lie face down · raise arms to Y at 45° — no weight needed' }],
  },

  'Tricep Rope Pushdown': {
    dumbbells:       [{ name:'Lying DB Tricep Extension', cue:'Lie flat · lower DBs to ears · elbows close · press to full lockout — great ROM' },
                      { name:'DB Overhead Tricep Extension', cue:'One or two hands · elbows close · full stretch overhead' }],
    bands:           [{ name:'Band Pushdown',                cue:'Anchor band overhead · elbows fixed · full extension' }],
    machines:        [{ name:'Machine Tricep Extension',     cue:'Adjust pad to upper arm · push down through full ROM' }],
    hammer_strength: [{ name:'Hammer Strength Dip',          cue:'Narrow grip · lean slightly forward · deep at bottom' }],
    kettlebells:     [{ name:'KB Tricep Extension',          cue:'Hold KB by horns overhead · lower behind head' }],
    bodyweight:      [{ name:'Bench Dip',                    cue:'Hands on bench behind you · chest tall · full depth' },
                      { name:'Diamond Push-Up',              cue:'Hands forming diamond shape — heavy tricep emphasis' }],
  },

  'Overhead DB Tricep Extension': {
    barbell:         [{ name:'EZ-Bar Skull Crusher',     cue:'Slight elbow flare — bar to forehead then extend' },
                      { name:'EZ-Bar Overhead Extension',cue:'Grip inside knurling · elbows close to ears' }],
    dumbbells:       [{ name:'Lying DB Tricep Extension', cue:'Lie flat · lower DBs to ears · elbows close · press to full lockout' },
                      { name:'DB Overhead Extension (seated)', cue:'Both hands grip one DB overhead · elbows close · full stretch' }],
    cables:          [{ name:'Cable Overhead Extension', cue:'Face away from stack · pull attachment behind head' }],
    bands:           [{ name:'Band Overhead Extension',  cue:'Stand on band · both hands overhead · press up' }],
    machines:        [{ name:'Machine Overhead Extension',cue:'Adjust seat for full overhead stretch' }],
    kettlebells:     [{ name:'KB Overhead Extension',    cue:'Hold single bell by horns overhead · lower behind head' }],
    bodyweight:      [{ name:'Diamond Push-Up',          cue:'Hands close together · direct tricep load' }],
  },

  // ── WORKOUT B ────────────────────────────────────────────────────────
  'Barbell Back Squat': {
    dumbbells:       [{ name:'DB Goblet Squat',          cue:'Hold DB at chest · elbows inside knees · upright torso' },
                      { name:'DB Front Squat',           cue:'DBs on shoulders in rack position · stay upright' }],
    machines:        [{ name:'Leg Press',                cue:'Feet shoulder-width · press through heels · full ROM' },
                      { name:'Hack Squat Machine',       cue:'Feet low and narrow for quad emphasis' }],
    hammer_strength: [{ name:'Hammer Strength Squat',    cue:'Lean into pad · drive through platform evenly' }],
    cables:          [{ name:'Cable Squat (goblet hold)',cue:'Low pulley · hold handle at chest · counterbalance' }],
    kettlebells:     [{ name:'KB Goblet Squat',          cue:'Hold bell at chest · elbows push knees out · depth' }],
    bands:           [{ name:'Band Squat',               cue:'Stand on band · loop over shoulders · add resistance' }],
    bodyweight:      [{ name:'Bodyweight Squat',         cue:'Arms forward for balance · full depth · 3-sec descent' },
                      { name:'Jump Squat',               cue:'Explosive version — for power / conditioning emphasis' }],
  },

  'Bulgarian Split Squat (DB)': {
    barbell:         [{ name:'Barbell BSS',              cue:'Bar on traps or front-rack · same mechanics apply' }],
    machines:        [{ name:'Hack Squat (Single Leg)', cue:'One leg on platform · step back off pad for split stance' }],
    cables:          [{ name:'Cable BSS',                cue:'Low pulley in opposite hand of front leg — core challenge' }],
    kettlebells:     [{ name:'KB Bulgarian Split Squat', cue:'Hold KBs at sides · same pattern as DB version' }],
    bands:           [{ name:'Band-Resisted Lunge',      cue:'Loop band around hips anchored behind — hip flexor emphasis' }],
    bodyweight:      [{ name:'Reverse Lunge',            cue:'Step back · drop knee toward floor · drive through heel' },
                      { name:'Walking Lunge',            cue:'Long stride · knee tracks over toe · upright torso' }],
  },

  'Leg Press': {
    barbell:         [{ name:'Barbell Front Squat',      cue:'Upper body more upright — more quad dominant' },
                      { name:'Hack Squat (Barbell)',     cue:'Bar behind legs · feet forward — challenging but effective' }],
    dumbbells:       [{ name:'DB Sumo Squat',            cue:'Wide stance · toes out · hold DB between legs' }],
    machines:        [{ name:'Hack Squat Machine',       cue:'Feet low for quad emphasis · full depth' }],
    kettlebells:     [{ name:'KB Goblet Squat',          cue:'High rep replacement for machine volume' }],
    bands:           [{ name:'Band Squat',               cue:'Heavy band load, slow tempo to match leg press stimulus' }],
    bodyweight:      [{ name:'Single-Leg Box Squat',     cue:'Sit back onto box · drive up through heel' }],
  },

  'Leg Extension': {
    cables:          [{ name:'Cable Leg Extension',      cue:'Ankle attachment · knee locked at full extension' }],
    bands:           [{ name:'Band Leg Extension',       cue:'Anchor band behind · sit on chair · extend against resistance' }],
    machines:        [{ name:'Seated Leg Extension',     cue:'Adjust pad to shin · extend to full lockout · slow eccentric' }],
    kettlebells:     [{ name:'KB Step-Up',               cue:'Box at knee height · drive up through heel of front leg' }],
    bodyweight:      [{ name:'Wall Sit Isometric Hold',  cue:'90° knee angle · hold 45-60 sec per set for sustained quad work' },
                      { name:'Step-Up',                  cue:'Box step height at knee · drive through heel at top' }],
  },

  'Standing Calf Raise': {
    machines:        [{ name:'Leg Press Calf Raise',      cue:'Feet low on platform · toes hanging off edge · full plantarflexion · slow eccentric · knees slightly bent' },
                      { name:'Seated Calf Raise',        cue:'Different angle targets soleus more — do both when possible' },
                      { name:'Donkey Calf Raise',        cue:'Hinge forward 90° — maximizes gastrocnemius stretch' }],
    dumbbells:       [{ name:'Single-Leg DB Calf Raise', cue:'Hold DB on same-side hand · full stretch at bottom' }],
    kettlebells:     [{ name:'KB Single-Leg Calf Raise', cue:'Hold KB for loading · free hand for light balance only' }],
    bands:           [{ name:'Band Calf Raise',          cue:'Stand on band · loop over shoulders · full ROM essential' }],
    bodyweight:      [{ name:'Single-Leg Bodyweight Calf Raise', cue:'Slow 3-sec eccentric · 15-20 reps per leg for volume' }],
  },

  'Hanging Leg Raise': {
    machines:        [{ name:"Captain's Chair Leg Raise", cue:'Posterior pelvic tilt before raising · control descent' }],
    cables:          [{ name:'Cable Knee-Up',             cue:'Ankle attachment · draw knees to chest against cable' }],
    bands:           [{ name:'Decline Sit-Up w/ Band',    cue:'Band adds top-range resistance · go slow through ROM' }],
    bodyweight:      [{ name:'Floor Leg Raise',           cue:'Lower back flat · raise legs to 90° · controlled descent' },
                      { name:'V-Up',                      cue:'Simultaneous upper and lower crunch — high difficulty' }],
  },

  'Ab Wheel Rollout': {
    cables:          [{ name:'Cable Crunch (kneeling)',   cue:'Flex at waist not hips · round spine fully through ROM' }],
    bands:           [{ name:'Band Anti-Extension Hold',  cue:'Band around wrist, anchor above · resist extension forces' }],
    machines:        [{ name:'Machine Ab Crunch',         cue:'Adjust weight for 10-15 rep range · full flexion each rep' }],
    bodyweight:      [{ name:'Plank to Pike',             cue:'Start in plank · drive hips up to pike then return' },
                      { name:'Bear Crawl',                cue:'Knees 2 inches off ground · slow controlled steps' }],
  },

  // ── WORKOUT C ────────────────────────────────────────────────────────
  'Barbell Bent-Over Row': {
    dumbbells:       [{ name:'DB Chest-Supported Row',    cue:'Lie prone on 45° bench · eliminates lower back involvement' },
                      { name:'Single-Arm DB Row',         cue:'Knee on bench · pull to hip · full stretch at bottom' }],
    cables:          [{ name:'Seated Cable Row (Close)',  cue:'Neutral grip · elbows past torso · hard scap squeeze' }],
    machines:        [{ name:'Seated Row Machine',        cue:'Chest pad stabilises torso — focus on back squeeze' }],
    hammer_strength: [{ name:'Hammer Strength Iso Row',   cue:'Single arm option for address imbalances' }],
    kettlebells:     [{ name:'KB Bent-Over Row',          cue:'Hinge at hips · row to hip · slow eccentric' }],
    bands:           [{ name:'Band Row',                  cue:'Anchor band in front · hinge back · row to torso' }],
    bodyweight:      [{ name:'Inverted Row (TRX/Bar)',    cue:'Body plank · pull chest to bar · retract scapulae' }],
  },

  'Lat Pulldown': {
    cables:          [{ name:'Close-Grip Lat Pulldown',     cue:'Supinated narrow grip · pull to chin · strong bicep assist' },
                      { name:'Single-Arm Lat Pulldown',     cue:'One arm at a time · better mind-muscle connection · full stretch' }],
    machines:        [{ name:'Hammer Strength Lat Pulldown', cue:'Lean back slightly · elbows drive down and back to hips' },
                      { name:'Assisted Pull-Up Machine',     cue:'Select counterweight · full dead hang each rep · chin clears bar' }],
    hammer_strength: [{ name:'Hammer Strength Pulldown',    cue:'Adjust seat height · elbows track straight down · full ROM' }],
    bands:           [{ name:'Band Lat Pulldown',           cue:'Anchor band overhead · kneel or sit · mimic cable path' }],
    bodyweight:      [{ name:'Pull-Up',                     cue:'Dead hang start · chin clears bar · full extension at bottom · no kipping' },
                      { name:'Negative Pull-Up',            cue:'Jump to top position · lower over 5 sec · builds strength toward full reps' }],
    dumbbells:       [{ name:'DB Pullover',                 cue:'Lie across bench · arms wide arc · feel lat stretch at the bottom' }],
    kettlebells:     [{ name:'KB Pullover',                 cue:'Same arc pattern as DB pullover · single bell' }],
  },

  'Seated Cable Row (Wide Grip)': {
    dumbbells:       [{ name:'DB Chest-Supported Row',    cue:'Prone on incline bench · wide elbows · rear delt focus' },
                      { name:'DB Prone Row',              cue:'Face down flat bench · arms out wide · squeeze at top' }],
    barbell:         [{ name:'Pendlay Row',               cue:'Bar starts on floor each rep · flat back · explosive pull' },
                      { name:'Chest-Supported BB Row',   cue:'Prone on incline bench · full hang at bottom' }],
    bands:           [{ name:'Band Seated Row',           cue:'Anchor band in front · sit tall · row to lower sternum' }],
    machines:        [{ name:'Row Machine (Wide)',        cue:'Select wide grip attachment · elbows drive out and back' }],
    hammer_strength: [{ name:'Hammer Strength Row',       cue:'Unilateral or bilateral · full stretch and contraction' }],
    kettlebells:     [{ name:'KB Renegade Row',           cue:'Plank on KBs · alternate rows · anti-rotation challenge' }],
    bodyweight:      [{ name:'Wide-Grip Inverted Row',    cue:'Hands wider than shoulders · elbows flare · rear delt hit' }],
  },

  'Face Pull': {
    bands:           [{ name:'Band Face Pull',            cue:'Anchor at head height · pull to forehead · externally rotate' }],
    dumbbells:       [{ name:'DB Rear Delt Row',          cue:'Hinge 45° · elbows flare wide · think Face Pull angle' }],
    machines:        [{ name:'Reverse Pec Deck',          cue:'Arms parallel to floor · elbows slightly bent · wide arc' }],
    cables:          [{ name:'Single-Arm Cable Face Pull',cue:'One hand at a time — stronger mind-muscle connection' }],
    kettlebells:     [{ name:'KB Halo',                   cue:'Circle bell around head — shoulder and upper back health' }],
    bodyweight:      [{ name:'Prone W Raise',             cue:'Face down · arms in W shape · retract and depress scaps' }],
  },

  'DB Rear Delt Fly': {
    cables:          [{ name:'Cable Rear Delt Fly',       cue:'Cross cables · pull wide arcs · squeeze rear delts' }],
    machines:        [{ name:'Reverse Pec Deck',          cue:'Adjust to chest height · arc back as far as possible' }],
    hammer_strength: [{ name:'Hammer Strength Rear Delt', cue:'Adjust pad height · full ROM arc each rep' }],
    bands:           [{ name:'Band Rear Delt Fly',        cue:'Anchor band at chest height · pull to sides' }],
    barbell:         [{ name:'Prone BB Rear Delt Row',    cue:'Face down on bench · wide grip · shrug elbows to ceiling' }],
    kettlebells:     [{ name:'KB Rear Delt Swing',        cue:'Same fly motion · bell provides natural arc' }],
    bodyweight:      [{ name:'Prone T Raise',             cue:'Arms straight out · lift off floor — pure rear delt work' }],
  },

  'Barbell Curl': {
    dumbbells:       [{ name:'Alternating DB Curl',       cue:'Supinate at top · don\'t swing · slow 3-sec eccentric' },
                      { name:'DB Preacher Curl',          cue:'Eliminates cheating · full stretch at bottom' }],
    cables:          [{ name:'Cable Curl (EZ-bar)',       cue:'Constant tension throughout ROM — great for peak contraction' },
                      { name:'High Cable Curl',           cue:'Arms up at shoulder height · curl toward ears — peak focus' }],
    machines:        [{ name:'Machine Preacher Curl',     cue:'Full stretch · no cheat · perfect isolation' }],
    bands:           [{ name:'Band Curl',                 cue:'Stand on band · both hands · slow eccentric is key' }],
    kettlebells:     [{ name:'KB Curl',                   cue:'Neutral grip or supinate — bell challenges at different angles' }],
    bodyweight:      [{ name:'Underhand Inverted Row',    cue:'Supinated grip · curling motion — compound bicep work' }],
  },

  'Hammer Curl': {
    barbell:         [{ name:'Cross-Body Hammer Curl',    cue:'DB crosses midline to opposite shoulder · long head emphasis' }],
    cables:          [{ name:'Rope Hammer Curl',          cue:'Rope attachment · neutral grip · full extension at bottom' }],
    machines:        [{ name:'Machine Neutral Curl',      cue:'Neutral grip handles if available · smooth resistance curve' }],
    bands:           [{ name:'Band Hammer Curl',          cue:'Stand on band · neutral grip · squeeze at top' }],
    kettlebells:     [{ name:'KB Hammer Curl',            cue:'Hold by handle · neutral wrist · curl to shoulder' }],
    bodyweight:      [{ name:'Chin-Up (neutral grip)',    cue:'Neutral/parallel grip bar · compound hammer curl pattern' }],
  },

  'Leaning Cable Lateral Raise': {
    cables:          [{ name:'Behind-the-Back Cable Lateral Raise', cue:'Cable behind back — constant tension through full ROM' },
                      { name:'Single-Arm Cable Lateral (High)',  cue:'Pull cable across body downward — reverse-lengthened stimulus' }],
    dumbbells:       [{ name:'DB Lateral Raise (Lying)',         cue:'Lie on side on bench · raise top arm to ceiling · maximises stretch at bottom' },
                      { name:'DB Lateral Raise',                 cue:'Standard DB lateral — lead with elbow, thumb down at top' }],
    machines:        [{ name:'Machine Lateral Raise',            cue:'Pad on upper forearm · full ROM · slow eccentric' }],
    bands:           [{ name:'Band Lateral Raise',               cue:'Stand on band · bilateral or single-arm' }],
    kettlebells:     [{ name:'KB Lateral Raise',                 cue:'Same arc as DB — control the eccentric phase' }],
    bodyweight:      [{ name:'Wall Lateral Raise',               cue:'Stand facing wall · raise arm along wall — isolates delt without momentum' }],
  },

  'DB Lateral Raise': {
    cables:          [{ name:'Cable Lateral Raise',       cue:'Low pulley · constant tension entire arc' }],
    bands:           [{ name:'Band Lateral Raise',        cue:'Doubled band for higher resistance · slow and controlled' }],
    machines:        [{ name:'Machine Lateral Raise',     cue:'Pad on forearm — removes grip fatigue · pure delt' }],
    kettlebells:     [{ name:'KB Lateral Raise',          cue:'Hold by horns · thumb down at top for peak activation' }],
    barbell:         [{ name:'Upright Row (wide grip)',   cue:'Wide grip reduces impingement risk · elbows lead' }],
    bodyweight:      [{ name:'Prone Y Raise',             cue:'Lie face down · arms at 45° — scapular health bonus' }],
  },

  // ── WORKOUT D ────────────────────────────────────────────────────────
  'Romanian Deadlift (RDL)': {
    dumbbells:       [{ name:'DB Romanian Deadlift',      cue:'Same hinge pattern · DBs track close to legs' },
                      { name:'Single-Leg DB RDL',         cue:'Balance challenge · excellent hamstring isolation per side' }],
    cables:          [{ name:'Cable Pull-Through',        cue:'Low pulley · hip hinge · drive hips forward aggressively' }],
    machines:        [{ name:'Leg Curl (stiff-leg focus)',cue:'Straighten knee more than usual for hamstring stretch' }],
    bands:           [{ name:'Band Good Morning',         cue:'Band on traps · hinge back · feel hamstring tension' }],
    kettlebells:     [{ name:'KB RDL',                    cue:'Same hinge pattern · bell hangs between legs' },
                      { name:'KB Single-Leg RDL',         cue:'Bell in opposite hand to standing leg — natural counter-balance' }],
    bodyweight:      [{ name:'Bodyweight Single-Leg RDL', cue:'Arms forward for balance · slow and controlled per side' }],
  },

  'Barbell Hip Thrust': {
    dumbbells:       [{ name:'DB Hip Thrust',             cue:'DBs on hip crests · same mechanics · lighter load ceiling' }],
    machines:        [{ name:'Hip Thrust Machine',        cue:'Adjustable pad on hips · often allows heavier loading' },
                      { name:'Glute Bridge Machine',      cue:'Lying position · reduces upper body setup time' }],
    hammer_strength: [{ name:'Hammer Strength Hip Press', cue:'Seated version of hip extension — adjust pad placement' }],
    cables:          [{ name:'Cable Hip Extension',       cue:'Ankle attachment · standing hip hinge into extension' }],
    kettlebells:     [{ name:'KB Hip Thrust',             cue:'Bell at hip crease · same glute squeeze cue at top' }],
    bands:           [{ name:'Banded Hip Thrust',         cue:'Band across hips adds top-range resistance — peak glute work' }],
    bodyweight:      [{ name:'Single-Leg Glute Bridge',   cue:'High reps per side · pause 2 sec at top for activation' }],
  },

  'Lying Leg Curl': {
    cables:          [{ name:'Standing Cable Leg Curl',   cue:'Ankle attachment · one leg at a time · full knee flex' }],
    bands:           [{ name:'Band Leg Curl',             cue:'Anchor band at ground in front · curl against resistance' }],
    machines:        [{ name:'Seated Leg Curl Machine',   cue:'Seated version — different hamstring emphasis · try both' }],
    dumbbells:       [{ name:'DB Leg Curl (lying)',       cue:'DB between feet · curl toward glutes · slow eccentric' }],
    kettlebells:     [{ name:'KB Hamstring Curl (slider)',cue:'Heels on KB · bridge up · pull KBs toward glutes' }],
    bodyweight:      [{ name:'Nordic Hamstring Curl',     cue:'Knees anchored · lower as slow as possible · hardest BW option' },
                      { name:'Slider Leg Curl',           cue:'Slide heel toward glutes on smooth surface · bridges combined' }],
  },

  'Cable Pull-Through': {
    bands:           [{ name:'Band Pull-Through',         cue:'Anchor band to fixed point · same hip hinge pattern' }],
    barbell:         [{ name:'Good Morning',              cue:'Bar on traps · hinge at hips · feel hamstring tension' }],
    dumbbells:       [{ name:'DB Sumo Deadlift',          cue:'Wide stance · DB between legs · hinge to floor' }],
    kettlebells:     [{ name:'KB Swing',                  cue:'Explosive hip drive — ballistic version of same pattern' },
                      { name:'KB Deadlift',               cue:'Slower and controlled — matches pull-through stimulus' }],
    bodyweight:      [{ name:'Hip Hinge (BW Good Morning)', cue:'Hands on hips · sit back · feel hamstring load · RDL pattern' }],
    machines:        [{ name:'Glute Kickback Machine',    cue:'Different angle but similar posterior chain activation' }],
  },

  'Single-Leg Calf Raise': {
    dumbbells:       [{ name:'Single-Leg DB Calf Raise',         cue:'Hold DB in same-side hand · stand on edge · full ROM' }],
    machines:        [{ name:'Leg Press Calf Raise (Single-Leg)', cue:'One foot on platform · full plantarflexion · controlled return' }],
    cables:          [{ name:'Cable Single-Leg Calf Raise',      cue:'Low cable attachment · slight forward lean · full stretch' }],
    bands:           [{ name:'Band Single-Leg Calf Raise',       cue:'Stand on band with one foot · use wall for balance' }],
    barbell:         [{ name:'Single-Leg Barbell Calf Raise',    cue:'Bar on traps · stand on elevated surface · one foot at a time' }],
    bodyweight:      [{ name:'Bodyweight Single-Leg Calf Raise', cue:'Pure bodyweight · stand on a step · slow eccentric · high reps' }],
  },

  'Seated Calf Raise': {
    machines:        [{ name:'Leg Press Calf Raise',      cue:'Feet low on platform · toes off edge · full ROM · targets gastroc similarly to standing — great machine option' },
                      { name:'Standing Calf Raise',       cue:'Gastroc dominant — different muscle emphasis than seated' },
                      { name:'Donkey Calf Raise',         cue:'Best gastrocnemius stretch of any calf exercise' }],
    dumbbells:       [{ name:'DB Seated Calf Raise',      cue:'DB on quads · slow full-ROM reps · feel the stretch' }],
    bands:           [{ name:'Seated Band Calf Raise',    cue:'Band around arch of foot · extend against resistance' }],
    kettlebells:     [{ name:'KB Seated Calf Raise',      cue:'KB on quad for loading · same seated mechanics' }],
    bodyweight:      [{ name:'Seated BW Calf Raise',      cue:'High volume (25+ reps) compensates for lower load' }],
  },

  'Cable Crunch': {
    bands:           [{ name:'Band Crunch',               cue:'Anchor band above · kneel and flex spine — same pattern' }],
    machines:        [{ name:'Ab Machine Crunch',         cue:'Arms cross over chest or hands behind head · full flex' }],
    dumbbells:       [{ name:'DB Crunch',                 cue:'Hold DB at chest · slow tempo · don\'t use momentum' }],
    barbell:         [{ name:'Ab Wheel Rollout',          cue:'Barbell can be used instead of ab wheel — same muscles' }],
    kettlebells:     [{ name:'KB Windmill',               cue:'Core anti-rotation and flexion combined — high difficulty' }],
    bodyweight:      [{ name:'Crunch / Sit-Up',           cue:'High rep volume (25-30) with bodyweight to compensate' },
                      { name:'V-Up',                      cue:'Advanced — upper and lower crunch simultaneously' }],
  },

  'Pallof Press (per side)': {
    bands:           [{ name:'Band Pallof Press',         cue:'Anchor band at chest height · press and resist rotation' }],
    cables:          [{ name:'Half-Kneeling Pallof Press',cue:'Kneeling version increases hip flexor involvement' }],
    dumbbells:       [{ name:'DB Rotational Press',       cue:'Press DB while rotating torso — dynamic anti-rotation' }],
    machines:        [{ name:'Landmine Rotation',         cue:'Barbell in landmine — sweep arc with arms · core fights resist' }],
    kettlebells:     [{ name:'KB Windmill',               cue:'Lateral flexion + rotation — advanced core stability work' }],
    bodyweight:      [{ name:'Side Plank',                cue:'Hold 30-45 sec per side · hips up throughout · scales easily' },
                      { name:'Dead Bug',                  cue:'Opposite arm/leg extend · lower back stays flat — anti-extension' }],
  },

  // ── Added with RP / Sculpt / Vitality programs ──────────────────────
  'Weighted Pull-Up': {
    bodyweight:      [{ name:'Pull-Up',                    cue:'Full dead hang · chin over bar · controlled descent' },
                      { name:'Chin-Up',                    cue:'Supinated grip · more biceps · full ROM' }],
    machines:        [{ name:'Assisted Pull-Up Machine',  cue:'Knee on pad assists — scale assistance down over time' },
                      { name:'Lat Pulldown',               cue:'Seated vertical pull · same pattern · adjustable load' }],
    cables:          [{ name:'Lat Pulldown',               cue:'Wide grip · pull to upper chest · full overhead stretch' }],
    bands:           [{ name:'Band-Assisted Pull-Up',     cue:'Loop band on bar · foot in band · assists the bottom' }],
    hammer_strength: [{ name:'Hammer Strength Pulldown',  cue:'Plate-loaded · independent arms · strong stretch at top' }],
  },
  'Dumbbell Row': {
    dumbbells:       [{ name:'Chest-Supported DB Row',    cue:'Face-down on incline bench · no momentum · pure back' }],
    barbell:         [{ name:'Barbell Bent-Over Row',      cue:'Hinge 45° · drive elbows back · full stretch' },
                      { name:'Pendlay Row',               cue:'Bar resets on floor each rep · explosive concentric' }],
    cables:          [{ name:'Single-Arm Cable Row',      cue:'Constant tension · full stretch and squeeze' },
                      { name:'Seated Cable Row',           cue:'Tall spine · drive elbows back · 2-sec squeeze' }],
    machines:        [{ name:'Machine Row',                cue:'Chest on pad · isolate the back without stabilising' }],
    hammer_strength: [{ name:'Hammer Strength Row',        cue:'Plate-loaded · independent arms · big stretch and squeeze' }],
    kettlebells:     [{ name:'KB Row',                     cue:'Brace on bench · row to hip · control the eccentric' }],
    bands:           [{ name:'Band Row',                   cue:'Anchor at waist height · row to ribs · squeeze' }],
    bodyweight:      [{ name:'Inverted Row',               cue:'Bar at hip height · body straight · pull chest to bar' }],
  },
  'Seated Cable Row': {
    cables:          [{ name:'Single-Arm Cable Row',      cue:'One side at a time · rotate slightly for full ROM' },
                      { name:'Wide-Grip Cable Row',        cue:'Wide bar · elbows flare · upper-back emphasis' }],
    machines:        [{ name:'Machine Row',                cue:'Chest-supported · stable · drive elbows back' }],
    hammer_strength: [{ name:'Hammer Strength Row',        cue:'Plate-loaded · independent arms · strong squeeze' }],
    dumbbells:       [{ name:'Chest-Supported DB Row',    cue:'Incline bench · no body english · pure mid-back' },
                      { name:'Dumbbell Row',               cue:'Brace on bench · elbow to ceiling · full stretch' }],
    barbell:         [{ name:'Barbell Bent-Over Row',      cue:'Hinge · overhand grip · drive elbows back' }],
    bands:           [{ name:'Seated Band Row',            cue:'Band around feet · tall posture · row to waist' }],
    bodyweight:      [{ name:'Inverted Row',               cue:'Under a bar · heels down · pull chest up' }],
    kettlebells:     [{ name:'KB Row',                     cue:'Single-arm · braced · row to hip' }],
  },
  'Seated DB Shoulder Press': {
    dumbbells:       [{ name:'Standing DB Press',          cue:'Brace core · press overhead · no leg drive' },
                      { name:'Arnold Press',               cue:'Rotate palms through the press · full delt sweep' }],
    barbell:         [{ name:'Overhead Press',             cue:'Bar on front delts · press to lockout · squeeze glutes' },
                      { name:'Push Press',                 cue:'Slight leg drive to start · for heavier loads' }],
    machines:        [{ name:'Machine Shoulder Press',     cue:'Back supported · fixed path · safe to push' }],
    hammer_strength: [{ name:'Hammer Strength Shoulder Press', cue:'Plate-loaded · independent arms · strong lockout' }],
    cables:          [{ name:'Cable Shoulder Press',       cue:'Dual low pulleys · constant tension overhead' }],
    kettlebells:     [{ name:'KB Overhead Press',          cue:'Bell in rack · press to lockout · stack the joints' }],
    bands:           [{ name:'Band Overhead Press',        cue:'Stand on band · press up · resist the pull down' }],
    bodyweight:      [{ name:'Pike Push-Up',               cue:'Hips high · head between hands · vertical pressing' }],
  },
  'Cable Lateral Raise': {
    dumbbells:       [{ name:'DB Lateral Raise',           cue:'3-sec eccentric · slight lean · thumb down at top' }],
    machines:        [{ name:'Machine Lateral Raise',      cue:'Pads on outer arms · constant resistance · pure delt' }],
    bands:           [{ name:'Band Lateral Raise',         cue:'Stand on band · raise to shoulder height · control down' }],
    kettlebells:     [{ name:'KB Lateral Raise',           cue:'Control the offset load carefully · slow eccentric' }],
    cables:          [{ name:'Leaning Cable Lateral Raise',cue:'Lean away from stack · maximises the stretched position' }],
    bodyweight:      [{ name:'Wall Lateral Raise',         cue:'Face wall · raise arm along it · isometric burn' }],
  },
  'Rope Tricep Pushdown': {
    cables:          [{ name:'Straight-Bar Pushdown',      cue:'Elbows pinned · full lockout · squeeze the triceps' },
                      { name:'Single-Arm Cable Pushdown',  cue:'One arm · full ROM · fix any side-to-side imbalance' }],
    dumbbells:       [{ name:'DB Overhead Extension',      cue:'Both hands on one bell · full overhead stretch' },
                      { name:'DB Kickback',                cue:'Hinge over · elbow high · extend and squeeze' }],
    barbell:         [{ name:'EZ-Bar Skull Crusher',       cue:'Lower to forehead · long-head stretch · lockout' },
                      { name:'Close-Grip Bench Press',     cue:'Hands shoulder-width · elbows tucked · press' }],
    machines:        [{ name:'Tricep Extension Machine',   cue:'Fixed path · isolate without stabilising' }],
    hammer_strength: [{ name:'Hammer Strength Dip',        cue:'Plate-loaded dip · lean upright for triceps' }],
    bands:           [{ name:'Band Pushdown',              cue:'Anchor high · push down to lockout · squeeze' }],
    kettlebells:     [{ name:'KB Overhead Extension',      cue:'Bell behind head · extend to lockout · control' }],
    bodyweight:      [{ name:'Bench Dip',                  cue:'Hands on bench · lower to 90° · press up' },
                      { name:'Diamond Push-Up',            cue:'Hands together · elbows tucked · tricep-biased push' }],
  },
  'Chest Press Machine': {
    machines:        [{ name:'Smith Machine Bench Press',  cue:'Fixed bar path · safe to push near failure solo' }],
    hammer_strength: [{ name:'Hammer Strength Chest Press',cue:'Plate-loaded · independent arms · strong contraction' }],
    dumbbells:       [{ name:'DB Bench Press',             cue:'Full ROM · deep stretch · stabilise the bells' },
                      { name:'DB Floor Press',             cue:'Floor limits depth · joint-friendly pressing' }],
    barbell:         [{ name:'Barbell Bench Press',         cue:'Retract scapula · controlled descent · drive up' }],
    cables:          [{ name:'Cable Chest Press',          cue:'Dual pulleys · press and squeeze · constant tension' }],
    bands:           [{ name:'Band Chest Press',           cue:'Band behind back · press forward · resist the return' }],
    bodyweight:      [{ name:'Push-Up',                    cue:'Plank line · full ROM · elevate hands to scale down' }],
  },
  'Goblet Squat': {
    dumbbells:       [{ name:'DB Goblet Squat',            cue:'Hold bell at chest · sit between hips · upright torso' }],
    kettlebells:     [{ name:'KB Goblet Squat',            cue:'Bell by the horns · elbows inside knees at depth' },
                      { name:'KB Front Squat',             cue:'Double bell rack position · brace hard' }],
    barbell:         [{ name:'Barbell Front Squat',        cue:'Bar on front delts · elbows high · upright' },
                      { name:'Barbell Back Squat',          cue:'Brace · sit to depth · drive knees out' }],
    machines:        [{ name:'Leg Press',                  cue:'Back supported · full ROM · safest loaded option' },
                      { name:'Hack Squat',                 cue:'Shoulders under pads · constant quad tension' }],
    bodyweight:      [{ name:'Bodyweight Squat',           cue:'Sit back and down · full depth · chest up' }],
    bands:           [{ name:'Band Squat',                 cue:'Band under feet to shoulders · resist standing' }],
  },
  'Hack Squat': {
    machines:        [{ name:'Hack Squat Machine',         cue:'Shoulders under pads · feet mid-platform · full depth' },
                      { name:'Leg Press',                  cue:'Feet low and narrow for quads · full ROM' }],
    hammer_strength: [{ name:'V-Squat Machine',            cue:'Plate-loaded squat pattern · constant quad tension' }],
    barbell:         [{ name:'Barbell Back Squat',          cue:'Brace · sit to depth · drive knees out' },
                      { name:'Barbell Front Squat',         cue:'Front rack · upright torso · quad-biased' }],
    dumbbells:       [{ name:'DB Goblet Squat',            cue:'Bell at chest · upright · full depth' }],
    cables:          [{ name:'Cable Squat',                cue:'Hold low pulley · sit back · constant tension' }],
    kettlebells:     [{ name:'KB Goblet Squat',            cue:'Bell by horns · elbows inside knees at depth' }],
    bodyweight:      [{ name:'Bulgarian Split Squat',      cue:'Rear foot elevated · unilateral quad load' }],
  },
  'Bulgarian Split Squat': {
    dumbbells:       [{ name:'DB Bulgarian Split Squat',   cue:'Bell each hand · rear foot up · drop straight down' }],
    barbell:         [{ name:'Barbell Bulgarian Split Squat', cue:'Bar on back · controlled · long stride for glute' }],
    kettlebells:     [{ name:'KB Goblet Split Squat',      cue:'Bell at chest · upright · rear foot elevated' }],
    machines:        [{ name:'Smith Bulgarian Split Squat',cue:'Fixed path adds stability · focus on the working leg' }],
    bodyweight:      [{ name:'Bodyweight Split Squat',     cue:'Rear foot up · drop down · drive through front heel' },
                      { name:'Reverse Lunge',              cue:'Step back · drop knee · drive up — easier on balance' }],
    bands:           [{ name:'Band Split Squat',           cue:'Stand on band · front foot loaded · resist standing' }],
  },
  'Walking Lunge': {
    dumbbells:       [{ name:'DB Walking Lunge',           cue:'Bell each hand · long steps · drop the back knee' }],
    barbell:         [{ name:'Barbell Walking Lunge',       cue:'Bar on back · controlled steps · stay tall' }],
    kettlebells:     [{ name:'KB Walking Lunge',           cue:'Bells at sides or racked · long stride for glute' }],
    machines:        [{ name:'Smith Lunge',                cue:'Fixed bar · stationary lunge · stable for balance' }],
    bodyweight:      [{ name:'Bodyweight Walking Lunge',   cue:'Long steps · push through the front heel' },
                      { name:'Reverse Lunge',              cue:'Step back in place · easier on the knees and balance' }],
    bands:           [{ name:'Band Lunge',                 cue:'Stand on band · front-leg loaded · controlled' }],
  },
  'Step-Up': {
    bodyweight:      [{ name:'Bodyweight Step-Up',         cue:'Low step · whole foot · step down slowly · hold a rail' }],
    dumbbells:       [{ name:'DB Step-Up',                 cue:'Bell each hand · drive through the top foot' }],
    barbell:         [{ name:'Barbell Step-Up',            cue:'Bar on back · controlled · only when balance is solid' }],
    kettlebells:     [{ name:'KB Step-Up',                 cue:'Bells racked or at sides · drive up tall' }],
    bands:           [{ name:'Band Step-Up',               cue:'Stand on band · adds resistance at the top' }],
    machines:        [{ name:'Leg Press',                  cue:'Single-leg press if balance is a concern' }],
  },
  'Sit-to-Stand': {
    bodyweight:      [{ name:'Chair Squat',               cue:'Sit to a chair and stand · tap-and-go · controlled' },
                      { name:'Box Squat',                  cue:'Sit to a box at comfortable height · stand briskly' }],
    dumbbells:       [{ name:'Goblet Sit-to-Stand',       cue:'Hold a light DB at chest · stand fast, sit slow' }],
    kettlebells:     [{ name:'KB Goblet Sit-to-Stand',    cue:'Bell at chest · brisk stand · 3-sec lower' }],
    machines:        [{ name:'Leg Press',                 cue:'Back supported alternative to load the legs safely' }],
    bands:           [{ name:'Band-Assisted Sit-to-Stand',cue:'Band overhead assists the stand · build confidence' }],
  },
  'Leg Curl': {
    machines:        [{ name:'Lying Leg Curl',            cue:'Plantarflex at peak · slow eccentric · full stretch' },
                      { name:'Seated Leg Curl',            cue:'Trains the lengthened position · controlled' }],
    dumbbells:       [{ name:'DB Leg Curl',               cue:'Bell between feet · curl lying face-down · slow' }],
    bands:           [{ name:'Band Leg Curl',             cue:'Anchor band at ankle · curl heel to glute' }],
    bodyweight:      [{ name:'Nordic Curl',               cue:'Anchor ankles · lower slowly · very challenging — scale ROM' },
                      { name:'Slider Leg Curl',            cue:'Heels on sliders · bridge up · curl heels in' }],
    cables:          [{ name:'Cable Leg Curl',            cue:'Ankle strap · curl heel to glute · constant tension' }],
    kettlebells:     [{ name:'KB Leg Curl',               cue:'Bell between feet · controlled curl face-down' }],
  },
  'Seated Leg Curl': {
    machines:        [{ name:'Lying Leg Curl',            cue:'Plantarflex at peak · slow eccentric · full stretch' }],
    dumbbells:       [{ name:'DB Leg Curl',               cue:'Bell between feet · curl lying face-down · slow' }],
    bands:           [{ name:'Band Leg Curl',             cue:'Anchor at ankle height · curl heel to glute' }],
    bodyweight:      [{ name:'Nordic Curl',               cue:'Anchor ankles · slow lower · scale the range' },
                      { name:'Slider Leg Curl',            cue:'Heels on sliders · hips up · curl in' }],
    cables:          [{ name:'Cable Leg Curl',            cue:'Ankle strap · curl heel to glute' }],
  },
  'Cable Glute Kickback': {
    cables:          [{ name:'Standing Cable Kickback',   cue:'Ankle strap · hinge slightly · drive heel back and up' }],
    machines:        [{ name:'Glute Kickback Machine',    cue:'Press pad back with the heel · squeeze at full extension' }],
    bands:           [{ name:'Band Kickback',             cue:'Band around ankles · drive one leg back · squeeze' },
                      { name:'Banded Glute Bridge',        cue:'Band above knees · bridge up · push knees out' }],
    bodyweight:      [{ name:'Quadruped Hip Extension',   cue:'On all fours · drive heel to ceiling · squeeze' },
                      { name:'Donkey Kick',               cue:'Bent knee · drive sole up · controlled' }],
    dumbbells:       [{ name:'DB Glute Bridge',           cue:'Bell on hips · bridge up · squeeze hard at top' }],
  },
  'Glute Bridge': {
    bodyweight:      [{ name:'Bodyweight Glute Bridge',   cue:'Drive hips up · squeeze · pause at the top' },
                      { name:'Single-Leg Glute Bridge',   cue:'One leg · level hips · harder unilateral version' }],
    barbell:         [{ name:'Barbell Hip Thrust',        cue:'Shoulders on bench · bar on hips · full lockout' }],
    dumbbells:       [{ name:'DB Glute Bridge',           cue:'Bell on hips · drive up · squeeze' }],
    bands:           [{ name:'Banded Glute Bridge',       cue:'Band above knees · push out as you bridge up' }],
    machines:        [{ name:'Glute Bridge Machine',      cue:'Pad on hips · drive up · controlled' }],
    kettlebells:     [{ name:'KB Glute Bridge',           cue:'Bell on hips · bridge and squeeze' }],
  },
  'Hip Abduction': {
    machines:        [{ name:'Hip Abduction Machine',     cue:'Lean forward to bias upper glute · push knees out · pause' }],
    cables:          [{ name:'Cable Hip Abduction',       cue:'Ankle strap · sweep leg out · control the return' }],
    bands:           [{ name:'Banded Lateral Walk',       cue:'Band above knees · step side to side · stay low' },
                      { name:'Seated Band Abduction',      cue:'Band around knees seated · press knees apart · squeeze' }],
    bodyweight:      [{ name:'Side-Lying Leg Raise',      cue:'Lie on side · raise top leg · slow up and down' },
                      { name:'Clamshell',                 cue:'Knees bent · open top knee · keep hips stacked' }],
  },
  'Hanging Knee Raise': {
    bodyweight:      [{ name:'Hanging Leg Raise',         cue:'Straight legs · raise to horizontal · no swing' },
                      { name:'Lying Leg Raise',           cue:'On the floor · lower slowly · keep low back down' }],
    machines:        [{ name:"Captain's Chair Knee Raise", cue:'Forearms on pads · raise knees · control down' }],
    cables:          [{ name:'Cable Crunch',              cue:'Kneel · crunch with the abs · round the spine' }],
    bands:           [{ name:'Banded Lying Leg Raise',    cue:'Band around feet · raise legs · resist down' }],
  },
  'Bird Dog': {
    bodyweight:      [{ name:'Dead Bug',                  cue:'On back · lower opposite arm and leg · keep back flat' },
                      { name:'Quadruped Reach',           cue:'On all fours · extend one arm at a time · stay square' }],
    bands:           [{ name:'Banded Bird Dog',           cue:'Light band on the working foot · adds gentle resistance' }],
  },
  'Dead Bug': {
    bodyweight:      [{ name:'Bird Dog',                  cue:'On all fours · extend opposite arm and leg · hold 2 sec' },
                      { name:'Plank',                     cue:'Forearm plank · brace · hold for time' }],
    bands:           [{ name:'Banded Dead Bug',           cue:'Hold band overhead · resist as you lower the legs' }],
    cables:          [{ name:'Cable Dead Bug',            cue:'Hold low cable overhead · anti-extension under load' }],
  },
  'Plank': {
    bodyweight:      [{ name:'Knee Plank',               cue:'Plank from the knees · easier · keep a straight line' },
                      { name:'Side Plank',               cue:'Hips up · hold per side · obliques and stability' },
                      { name:'RKC Plank',                cue:'Squeeze everything hard · short, maximal-tension holds' }],
    bands:           [{ name:'Banded Plank',             cue:'Band around forearms · press out · adds tension' }],
  },
  'Seated Cable Row (Wide)': {
    cables:          [{ name:'Seated Cable Row',          cue:'Neutral grip · drive elbows back · squeeze mid-back' },
                      { name:'Wide-Grip Cable Row',        cue:'Wide bar · elbows flare · upper-back emphasis' }],
    machines:        [{ name:'Wide-Grip Machine Row',     cue:'Chest-supported · elbows wide · upper-back focus' }],
    hammer_strength: [{ name:'Hammer Strength High Row',  cue:'Plate-loaded · wide path · big squeeze' }],
    dumbbells:       [{ name:'Wide DB Row',               cue:'Elbows out at 45° · pull to lower chest · upper back' }],
    barbell:         [{ name:'Wide-Grip Barbell Row',     cue:'Wide overhand grip · row to sternum · elbows high' }],
    bands:           [{ name:'Wide Band Row',             cue:'Anchor at chest height · pull wide to ribs · squeeze' }],
    bodyweight:      [{ name:'Wide Inverted Row',         cue:'Wide grip under a bar · pull chest up · elbows out' }],
  },
  'Weighted Dips': {
    bodyweight:      [{ name:'Dips',                      cue:'Lean forward for chest · full depth · controlled' },
                      { name:'Bench Dip',                 cue:'Hands on bench · feet out to scale up · triceps and chest' }],
    machines:        [{ name:'Assisted Dip Machine',     cue:'Knee on pad assists — reduce assistance over time' },
                      { name:'Chest Press Machine',       cue:'Seated press alternative · back supported' }],
    hammer_strength: [{ name:'Hammer Strength Dip',       cue:'Plate-loaded · lean forward for chest emphasis' }],
    barbell:         [{ name:'Close-Grip Bench Press',    cue:'Hands shoulder-width · elbows tucked · chest and triceps' }],
    dumbbells:       [{ name:'DB Floor Press',            cue:'Floor limits depth · joint-friendly pressing' },
                      { name:'DB Bench Press',            cue:'Full ROM · deep stretch · stabilise the bells' }],
    bands:           [{ name:'Band-Assisted Dip',         cue:'Band across the bars under the knees · assists the bottom' }],
  },
}
