import type { Program, WeekConfig, DayType, Workout } from '@/types'
import { rtfPercent, type Prescription } from './phatCustom'

// ═══════════════════════════════════════════════════════════════════════
// Bodybuilder Upper Body Focus — 5-Day
//
// Transcribed from the BB Upper Workout Builder export. Exercise
// selection rotates every week, so workouts are indexed per week.
// Weeks 1-11 run five days; WEEK 12 IS A TEST WEEK — two days only,
// opening with true max attempts (a 1RM, or a 3-rep max) followed by
// light accessory work.
//
// Two source features get first-class handling:
//   - BFR (blood-flow restriction) sets, marked in the source and
//     prescribed as 30,15,15 reps. These run at roughly 25% of 1RM with
//     cuffs, so they are flagged noOneRm and excluded from every 1RM
//     calculation - logging them as strength evidence would drag
//     estimates down badly.
//   - Rep schemes that differ per set (30,15,15) are shown verbatim
//     rather than averaged away.
//
// Source gives no loads or rest intervals; %1RM uses reps-to-failure and
// rest follows a hypertrophy profile - the app's interpretation.
// ═══════════════════════════════════════════════════════════════════════

export const BB_UPPER_ID = 'bb-upper-5day'

/** Typical BFR working load: ~25% of 1RM with cuffs applied. */
const BFR_PCT = 0.25

/** [dayKey][exercise][week] -> [sets, midReps, rir, repsLabel, flag, section]. */
const SCHEDULE: Record<string, Record<string, Record<number, [number, number, number, string, string, string]>>> = {
  A: {
    'Bench Press': { 1:[4,8,2,'8','','MAIN LIFTS'], 2:[4,8,1,'8','','MAIN LIFTS'], 3:[4,8,0,'8','','MAIN LIFTS'], 4:[3,8,3,'8','','MAIN LIFTS'], 5:[4,6,2,'6','','MAIN LIFTS'], 6:[4,6,1,'6','','MAIN LIFTS'], 7:[4,6,0,'6','','MAIN LIFTS'], 8:[3,6,3,'6','','MAIN LIFTS'], 9:[4,4,2,'4','','MAIN LIFTS'], 10:[4,4,1,'4','','MAIN LIFTS'], 11:[3,4,3,'4','','MAIN LIFTS'], 12:[1,1,0,'1','','REP TESTING'] },
    'Barbell Overhead Press': { 1:[4,8,2,'8','','MAIN LIFTS'], 2:[4,8,1,'8','','MAIN LIFTS'], 3:[4,8,0,'8','','MAIN LIFTS'], 4:[3,8,3,'8','','MAIN LIFTS'], 5:[4,6,2,'6','','MAIN LIFTS'], 6:[4,6,1,'6','','MAIN LIFTS'], 7:[4,6,0,'6','','MAIN LIFTS'], 8:[3,6,3,'6','','MAIN LIFTS'], 9:[4,4,2,'4','','MAIN LIFTS'], 10:[4,4,1,'4','','MAIN LIFTS'], 11:[3,4,3,'4','','MAIN LIFTS'] },
    'Machine Row': { 1:[3,15,1,'15','','ACCESSORY WORK'] },
    'Wide Grip Lat Pull-Down': { 1:[3,15,1,'15','','ACCESSORY WORK'], 7:[3,12,1,'12','','ACCESSORY WORK'] },
    'EZ-Bar Skull Crusher': { 1:[3,10,1,'10','','ACCESSORY WORK'], 3:[3,10,1,'10','','ACCESSORY WORK'], 11:[2,6,1,'6','','ACCESSORY WORK'] },
    'Dumbbell Curl': { 1:[3,10,1,'10','','ACCESSORY WORK'] },
    'Braced T-Bar Row': { 2:[3,15,1,'15','','ACCESSORY WORK'], 3:[3,15,1,'15','','ACCESSORY WORK'] },
    'Pullover Machine': { 2:[3,15,1,'15','','ACCESSORY WORK'], 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Machine Tricep Press-Down': { 2:[3,10,1,'10','','ACCESSORY WORK'], 9:[3,6,1,'6','','ACCESSORY WORK'] },
    'Preacher Curl': { 2:[3,10,1,'10','','ACCESSORY WORK'], 8:[2,8,1,'8','','ACCESSORY WORK'] },
    'Cable Pullover': { 3:[3,15,1,'15','','ACCESSORY WORK'] },
    'Concentration Curl': { 3:[3,10,1,'10','','ACCESSORY WORK'], 10:[3,6,1,'6','','ACCESSORY WORK'] },
    'Pendlay Row': { 4:[2,15,2,'15','','ACCESSORY WORK'], 6:[3,12,1,'12','','ACCESSORY WORK'] },
    'Pull-Up': { 4:[2,15,2,'15','','ACCESSORY WORK'], 11:[2,10,1,'10','','ACCESSORY WORK'] },
    'Single Arm Cable Press-Down': { 4:[2,10,2,'10','','ACCESSORY WORK'], 5:[3,8,1,'8','','ACCESSORY WORK'] },
    'Dumbbell Preacher Curl': { 4:[2,10,1,'10','','ACCESSORY WORK'], 9:[3,6,1,'6','','ACCESSORY WORK'] },
    'T-Bar Row': { 5:[3,12,1,'12','','ACCESSORY WORK'] },
    'Chin-Up': { 5:[3,12,1,'12','','ACCESSORY WORK'], 8:[2,12,2,'12','','ACCESSORY WORK'] },
    'Cambered Bar Curl': { 5:[3,8,1,'8','','ACCESSORY WORK'] },
    'Close Grip Lat Pull-Down': { 6:[3,12,1,'12','','ACCESSORY WORK'] },
    'Dumbbell Kickback': { 6:[3,8,1,'8','','ACCESSORY WORK'], 8:[2,8,2,'8','','ACCESSORY WORK'] },
    'Machine Curl': { 6:[3,8,1,'8','','ACCESSORY WORK'], 11:[2,6,1,'6','','ACCESSORY WORK'] },
    'Cable Row': { 7:[3,12,1,'12','','ACCESSORY WORK'], 9:[3,10,1,'10','','ACCESSORY WORK'], 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Cable Tricep Kickback': { 7:[3,8,1,'8','','ACCESSORY WORK'] },
    'Machine Preacher Curl': { 7:[3,8,1,'8','','ACCESSORY WORK'] },
    'Barbell Row': { 8:[2,12,2,'12','','ACCESSORY WORK'], 11:[2,10,1,'10','','ACCESSORY WORK'], 12:[1,3,0,'3','','REP TESTING'] },
    'Dumbbell Pullover': { 9:[3,10,1,'10','','ACCESSORY WORK'] },
    'V-Bar Cable Press-Down': { 10:[3,6,1,'6','','ACCESSORY WORK'] },
    'Back Squat': { 12:[1,1,0,'1','','REP TESTING'] },
    'Decline Cable Fly': { 12:[2,10,2,'10','','ACCESSORY WORK'] },
    'Machine Leg Extension': { 12:[2,10,2,'10','','ACCESSORY WORK'] },
    'Dumbbell Prone Row': { 12:[2,10,2,'10','','ACCESSORY WORK'] },
  },
  B: {
    'Back Squat': { 1:[4,8,2,'8','','MAIN LIFTS'], 2:[4,8,1,'8','','MAIN LIFTS'], 3:[4,8,0,'8','','MAIN LIFTS'], 4:[3,8,3,'8','','MAIN LIFTS'], 5:[4,6,2,'6','','MAIN LIFTS'], 6:[4,6,1,'6','','MAIN LIFTS'], 7:[4,6,0,'6','','MAIN LIFTS'], 8:[3,6,3,'6','','MAIN LIFTS'], 9:[4,4,2,'4','','MAIN LIFTS'], 10:[4,4,1,'4','','MAIN LIFTS'], 11:[3,4,0,'4','','MAIN LIFTS'] },
    'Hack Squat': { 1:[3,12,1,'12','','ACCESSORY WORK'] },
    'Stiff Legged Deadlift': { 1:[3,15,1,'15','','ACCESSORY WORK'], 9:[3,10,1,'10','','ACCESSORY WORK'] },
    'Prone Leg Curl': { 1:[3,15,1,'15','','ACCESSORY WORK'], 9:[3,10,1,'10','','ACCESSORY WORK'], 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Seated Calf Raise': { 1:[3,15,1,'15','','ACCESSORY WORK'], 11:[2,12,1,'12','','ACCESSORY WORK'] },
    'McGill Crunch': { 1:[3,15,0,'15','','CORE WORK'], 2:[3,15,0,'15','','CORE WORK'], 9:[3,15,0,'15','','CORE WORK'], 12:[3,15,0,'15','','CORE WORK'] },
    'Machine Squat': { 2:[3,12,1,'12','','ACCESSORY WORK'], 7:[3,10,1,'10','','ACCESSORY WORK'], 8:[2,10,2,'10','','ACCESSORY WORK'] },
    'Rack Deadlift': { 2:[3,15,1,'15','','ACCESSORY WORK'], 3:[3,15,1,'15','','ACCESSORY WORK'] },
    'Reverse Hyperextensions': { 2:[3,15,1,'15','','ACCESSORY WORK'], 3:[3,15,1,'15','','ACCESSORY WORK'], 6:[3,12,1,'12','','ACCESSORY WORK'] },
    'Leg Press Calf Raise': { 2:[3,15,1,'15','','ACCESSORY WORK'], 3:[3,15,1,'15','','ACCESSORY WORK'], 4:[2,15,1,'15','','ACCESSORY WORK'], 5:[3,12,1,'12','','ACCESSORY WORK'], 7:[3,12,1,'12','','ACCESSORY WORK'] },
    'Front Squat': { 3:[3,12,1,'12','','ACCESSORY WORK'] },
    'Bird Dogs': { 3:[3,15,0,'15','','CORE WORK'], 5:[3,15,0,'15','','CORE WORK'], 6:[3,15,0,'15','','CORE WORK'], 8:[3,15,0,'15','','CORE WORK'], 11:[3,15,0,'15','','CORE WORK'] },
    'Belt Squat': { 4:[2,12,2,'12','','ACCESSORY WORK'], 5:[3,10,1,'10','','ACCESSORY WORK'], 9:[3,8,1,'8','','ACCESSORY WORK'] },
    'Hyperextensions': { 4:[2,15,2,'15','','ACCESSORY WORK'], 11:[2,10,1,'10','','ACCESSORY WORK'], 12:[2,10,2,'10','','ACCESSORY WORK'] },
    'Dumbbell Leg Curl': { 4:[2,15,2,'15','','ACCESSORY WORK'], 5:[3,12,1,'12','','ACCESSORY WORK'], 8:[2,12,2,'12','','ACCESSORY WORK'] },
    'Deadbugs': { 4:[3,15,0,'15','','CORE WORK'], 7:[3,15,0,'15','','CORE WORK'] },
    'Romanian Deadlift': { 5:[3,12,1,'12','','ACCESSORY WORK'], 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Safety Bar Squat': { 6:[3,10,1,'10','','ACCESSORY WORK'] },
    'Deadlift from Boxes': { 6:[3,12,1,'12','','ACCESSORY WORK'], 7:[3,12,1,'12','','ACCESSORY WORK'] },
    'Standing Calf Raise': { 6:[3,12,1,'12','','ACCESSORY WORK'], 8:[2,12,1,'12','','ACCESSORY WORK'], 10:[3,12,1,'12','','ACCESSORY WORK'] },
    'Single Leg Curl': { 7:[3,12,1,'12','','ACCESSORY WORK'] },
    'Dumbbell Romanian Deadlift': { 8:[2,12,2,'12','','ACCESSORY WORK'] },
    'Donkey Calf Raise': { 9:[3,12,1,'12','','ACCESSORY WORK'] },
    'Leg Press': { 10:[3,8,1,'8','','ACCESSORY WORK'] },
    'Pallof Press': { 10:[3,15,0,'15','','CORE WORK'] },
    'Goblet Squat': { 11:[2,8,1,'8','','ACCESSORY WORK'] },
    'Glute Ham Raise': { 11:[2,10,1,'10','','ACCESSORY WORK'] },
    'Deadlift': { 12:[1,1,0,'1','','REP TESTING'] },
    'Pull-Up': { 12:[1,3,0,'3','','REP TESTING'] },
    'Machine Pull-Down': { 12:[2,10,2,'10','','ACCESSORY WORK'] },
    'Dumbbell Preacher Curl': { 12:[2,10,2,'10','','ACCESSORY WORK'] },
    'V-Bar Cable Press-Down': { 12:[2,10,2,'10','','ACCESSORY WORK'] },
  },
  C: {
    'Barbell Row': { 1:[4,8,2,'8','','MAIN LIFTS'], 2:[4,8,1,'8','','MAIN LIFTS'], 3:[4,8,0,'8','','MAIN LIFTS'], 4:[3,8,3,'8','','MAIN LIFTS'], 5:[4,6,2,'6','','MAIN LIFTS'], 6:[4,6,1,'6','','MAIN LIFTS'], 7:[4,6,0,'6','','MAIN LIFTS'], 8:[3,6,3,'6','','MAIN LIFTS'], 9:[4,4,2,'4','','MAIN LIFTS'], 10:[4,4,1,'4','','MAIN LIFTS'], 11:[3,4,0,'4','','MAIN LIFTS'] },
    'Pull-Up': { 1:[4,8,2,'8','','MAIN LIFTS'], 2:[4,8,1,'8','','MAIN LIFTS'], 3:[4,8,0,'8','','MAIN LIFTS'], 4:[3,8,3,'8','','MAIN LIFTS'], 5:[4,6,2,'6','','MAIN LIFTS'], 6:[4,6,1,'6','','MAIN LIFTS'], 7:[4,6,0,'6','','MAIN LIFTS'], 8:[3,6,3,'6','','MAIN LIFTS'], 9:[4,4,2,'4','','MAIN LIFTS'], 10:[4,4,1,'4','','MAIN LIFTS'], 11:[3,4,0,'4','','MAIN LIFTS'] },
    'Incline Barbell Press': { 1:[3,15,1,'15','','ACCESSORY WORK'], 2:[3,15,1,'15','','ACCESSORY WORK'] },
    'Arnold Press': { 1:[3,15,1,'15','','ACCESSORY WORK'], 3:[3,15,1,'15','','ACCESSORY WORK'], 6:[3,12,1,'12','','ACCESSORY WORK'] },
    'Cambered Bar Curl': { 1:[3,15,1,'15','','ACCESSORY WORK'], 2:[3,15,1,'15','','ACCESSORY WORK'], 5:[3,12,1,'12','','ACCESSORY WORK'], 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Overhead Rope Cable Extensions': { 1:[3,15,1,'15','','ACCESSORY WORK'], 2:[3,15,1,'15','','ACCESSORY WORK'], 3:[3,15,1,'15','','ACCESSORY WORK'], 5:[3,12,1,'12','','ACCESSORY WORK'], 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Push Jerk': { 2:[3,15,1,'15','','ACCESSORY WORK'], 4:[2,15,2,'15','','ACCESSORY WORK'], 8:[2,12,2,'12','','ACCESSORY WORK'] },
    'Close Grip Bench Press': { 3:[3,15,1,'15','','ACCESSORY WORK'] },
    'Dumbbell Preacher Curl': { 3:[3,15,1,'15','','ACCESSORY WORK'], 8:[2,12,2,'12','','ACCESSORY WORK'], 9:[3,10,1,'10','','ACCESSORY WORK'] },
    'Decline Machine Press': { 4:[2,15,2,'15','','ACCESSORY WORK'] },
    'Machine Preacher Curl': { 4:[2,15,2,'15','','ACCESSORY WORK'] },
    'Rope Press-Down': { 4:[2,15,2,'15','','ACCESSORY WORK'], 11:[2,10,1,'10','','ACCESSORY WORK'] },
    'Flat Machine Press': { 5:[3,12,1,'12','','ACCESSORY WORK'] },
    'Smith Machine Shoulder Press': { 5:[3,12,1,'12','','ACCESSORY WORK'], 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Dumbbell Floor Press': { 6:[3,12,1,'12','','ACCESSORY WORK'], 9:[3,10,1,'10','','ACCESSORY WORK'] },
    'Dumbbell Curl': { 6:[3,12,1,'12','','ACCESSORY WORK'], 7:[3,12,1,'12','','ACCESSORY WORK'] },
    'Cable Tricep Kickback': { 6:[3,12,1,'12','','ACCESSORY WORK'] },
    'Decline Dumbbell Chest Press': { 7:[3,12,1,'12','','ACCESSORY WORK'], 11:[2,10,1,'10','','ACCESSORY WORK'] },
    'Seated Dumbbell Press': { 7:[3,12,1,'12','','ACCESSORY WORK'], 11:[2,10,1,'10','','ACCESSORY WORK'] },
    'EZ-Bar Skull Crusher': { 7:[3,12,1,'12','','ACCESSORY WORK'] },
    'Decline Barbell Press': { 8:[2,12,2,'12','','ACCESSORY WORK'] },
    'Dumbbell Kickback': { 8:[2,12,2,'12','','ACCESSORY WORK'], 9:[3,10,1,'10','','ACCESSORY WORK'] },
    'Standing Military Press': { 9:[3,10,1,'10','','ACCESSORY WORK'] },
    'Incline Dumbbell Press': { 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Preacher Curl': { 11:[2,10,1,'10','','ACCESSORY WORK'] },
  },
  D: {
    'Deadlift': { 1:[4,8,2,'8','','MAIN LIFTS'], 2:[4,8,1,'8','','MAIN LIFTS'], 3:[4,8,0,'8','','MAIN LIFTS'], 4:[3,8,3,'8','','MAIN LIFTS'], 5:[4,6,2,'6','','MAIN LIFTS'], 6:[4,6,1,'6','','MAIN LIFTS'], 7:[4,6,0,'6','','MAIN LIFTS'], 8:[3,6,3,'6','','MAIN LIFTS'], 9:[4,4,2,'4','','MAIN LIFTS'], 10:[4,4,1,'4','','MAIN LIFTS'], 11:[3,4,0,'4','','MAIN LIFTS'] },
    'Romanian Deadlift': { 1:[3,12,1,'12','','ACCESSORY WORK'], 3:[3,12,1,'12','','ACCESSORY WORK'] },
    'Front Squat': { 1:[3,15,1,'15','','ACCESSORY WORK'], 3:[3,15,1,'15','','ACCESSORY WORK'], 7:[3,12,1,'12','','ACCESSORY WORK'], 9:[3,10,1,'10','','ACCESSORY WORK'], 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Banded Leg Extension': { 1:[3,15,1,'15','','ACCESSORY WORK'], 2:[3,15,1,'15','','ACCESSORY WORK'], 3:[3,15,1,'15','','ACCESSORY WORK'], 6:[3,12,1,'12','','ACCESSORY WORK'], 9:[3,10,1,'10','','ACCESSORY WORK'] },
    'Standing Calf Raise': { 1:[3,12,1,'12','','ACCESSORY WORK'], 7:[3,8,1,'8','','ACCESSORY WORK'] },
    'McGill Crunch': { 1:[3,12,0,'12','','CORE WORK'], 5:[3,10,0,'10','','CORE WORK'], 6:[3,10,0,'10','','CORE WORK'], 11:[3,10,0,'10','','CORE WORK'] },
    'Trap Bar Deadlift': { 2:[3,12,1,'12','','ACCESSORY WORK'] },
    'Leg Press': { 2:[3,15,1,'15','','ACCESSORY WORK'], 6:[3,12,1,'12','','ACCESSORY WORK'] },
    'Seated Calf Raise': { 2:[3,12,1,'12','','ACCESSORY WORK'], 6:[3,8,1,'8','','ACCESSORY WORK'], 8:[2,8,2,'8','','ACCESSORY WORK'], 10:[3,8,1,'8','','ACCESSORY WORK'] },
    'Pallof Press': { 2:[3,12,0,'12','','CORE WORK'], 3:[3,12,0,'12','','CORE WORK'] },
    'Leg Press Calf Raise': { 3:[3,12,1,'12','','ACCESSORY WORK'], 5:[3,8,1,'8','','ACCESSORY WORK'] },
    'Deadlift from Boxes': { 4:[2,12,2,'12','','ACCESSORY WORK'], 5:[3,10,1,'10','','ACCESSORY WORK'], 6:[3,10,1,'10','','ACCESSORY WORK'], 9:[3,8,1,'8','','ACCESSORY WORK'] },
    'Safety Bar Squat': { 4:[2,15,2,'15','','ACCESSORY WORK'] },
    'Sissy Squat': { 4:[2,15,2,'15','','ACCESSORY WORK'], 5:[3,12,1,'12','','ACCESSORY WORK'], 11:[2,10,1,'10','','ACCESSORY WORK'] },
    'Donkey Calf Raise': { 4:[2,12,2,'12','','ACCESSORY WORK'], 9:[3,8,1,'8','','ACCESSORY WORK'], 11:[2,8,1,'8','','ACCESSORY WORK'] },
    'Bird Dogs': { 4:[3,12,0,'12','','CORE WORK'], 8:[3,10,0,'10','','CORE WORK'] },
    'Goblet Squat': { 5:[3,12,1,'12','','ACCESSORY WORK'], 8:[2,12,2,'12','','ACCESSORY WORK'] },
    'Hyperextensions': { 7:[3,10,1,'10','','ACCESSORY WORK'] },
    'Machine Leg Extension': { 7:[3,12,1,'12','','ACCESSORY WORK'], 8:[2,12,2,'12','','ACCESSORY WORK'], 10:[3,10,1,'10','','ACCESSORY WORK'] },
    'Deadbugs': { 7:[3,10,0,'10','','CORE WORK'], 9:[3,10,0,'10','','CORE WORK'], 10:[3,10,0,'10','','CORE WORK'] },
    'Rack Deadlift': { 8:[2,10,2,'10','','ACCESSORY WORK'] },
    'Dumbbell Romanian Deadlift': { 10:[3,8,1,'8','','ACCESSORY WORK'], 11:[2,8,1,'8','','ACCESSORY WORK'] },
    'Machine Squat': { 11:[2,10,1,'10','','ACCESSORY WORK'] },
  },
  E: {
    'Incline Cable Fly': { 1:[3,12,1,'12','','ACCESSORY WORK'], 7:[3,10,1,'10','','ACCESSORY WORK'] },
    'Barbell Row': { 1:[3,12,1,'12','','ACCESSORY WORK'] },
    'Bent Over Dumbbell Lateral': { 1:[3,12,1,'12','','ACCESSORY WORK'] },
    'Chin-Up': { 1:[3,12,1,'12','','ACCESSORY WORK'], 8:[2,10,2,'10','','ACCESSORY WORK'] },
    'Concentration Curl': { 1:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'], 3:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'], 10:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Dumbbell Skull Crusher': { 1:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Flat Cable Fly': { 2:[3,12,1,'12','','ACCESSORY WORK'], 9:[3,8,1,'8','','ACCESSORY WORK'], 10:[3,8,1,'8','','ACCESSORY WORK'] },
    'Cable Row': { 2:[3,12,1,'12','','ACCESSORY WORK'], 6:[3,10,1,'10','','ACCESSORY WORK'] },
    'Front Lateral Raise': { 2:[3,12,1,'12','','ACCESSORY WORK'], 5:[3,10,1,'10','','ACCESSORY WORK'], 7:[3,10,1,'10','','ACCESSORY WORK'], 9:[3,8,1,'8','','ACCESSORY WORK'] },
    'Neutral Grip Pull-Up': { 2:[3,12,1,'12','','ACCESSORY WORK'], 6:[3,10,1,'10','','ACCESSORY WORK'], 10:[3,8,1,'8','','ACCESSORY WORK'] },
    'Machine Curl': { 2:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'EZ-Bar Skull Crusher': { 2:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'], 6:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Decline Dumbbell Fly': { 3:[3,12,1,'12','','ACCESSORY WORK'], 6:[3,10,1,'10','','ACCESSORY WORK'] },
    'T-Bar Row': { 3:[3,12,1,'12','','ACCESSORY WORK'], 5:[3,10,1,'10','','ACCESSORY WORK'], 8:[2,10,2,'10','','ACCESSORY WORK'], 10:[3,8,1,'8','','ACCESSORY WORK'] },
    'Reverse Pec Deck Fly': { 3:[3,12,1,'12','','ACCESSORY WORK'], 4:[2,12,2,'12','','ACCESSORY WORK'], 6:[3,10,1,'10','','ACCESSORY WORK'] },
    'Supinated Grip Pull-Up': { 3:[3,12,1,'12','','ACCESSORY WORK'] },
    'Machine Tricep Press-Down': { 3:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Incline Dumbbell Fly': { 4:[2,12,2,'12','','ACCESSORY WORK'], 11:[2,8,1,'8','','ACCESSORY WORK'] },
    'Prone Row': { 4:[2,12,2,'12','','ACCESSORY WORK'], 7:[3,10,1,'10','','ACCESSORY WORK'] },
    'Cable Pullover': { 4:[2,12,2,'12','','ACCESSORY WORK'] },
    'Decline Cable Fly': { 5:[3,10,1,'10','','ACCESSORY WORK'] },
    'Pullover Machine': { 5:[3,10,1,'10','','ACCESSORY WORK'] },
    'Cambered Bar Curl': { 5:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'], 9:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Dumbbell Kickback': { 5:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Dumbbell Preacher Curl': { 6:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'], 7:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Dumbbell Pullover': { 7:[3,10,1,'10','','ACCESSORY WORK'] },
    'V-Bar Cable Press-Down': { 7:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Pec Deck Machine': { 8:[2,10,2,'10','','ACCESSORY WORK'] },
    'Machine Lateral Raise': { 8:[2,10,2,'10','','ACCESSORY WORK'] },
    'Pendlay Row': { 9:[3,8,1,'8','','ACCESSORY WORK'], 11:[2,8,1,'8','','ACCESSORY WORK'] },
    'Pull-Up': { 9:[3,8,1,'8','','ACCESSORY WORK'] },
    'Rope Press-Down': { 9:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Lateral Raise': { 10:[3,8,1,'8','','ACCESSORY WORK'] },
    'Overhead Rope Cable Extensions': { 10:[3,22,0,'30,15,15','BFR','ACCESSORY WORK'] },
    'Upright Row': { 11:[2,8,1,'8','','ACCESSORY WORK'] },
    'Wide Grip Lat Pull-Down': { 11:[2,8,1,'8','','ACCESSORY WORK'] },
  },
}

const WEEK_WORKOUTS: Record<number, Workout[]> = {
  1: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Machine Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Wide Grip Lat Pull-Down', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Hack Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Stiff Legged Deadlift', muscle: 'Hamstrings', type: 'isolation', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Prone Leg Curl', muscle: 'Hamstrings', type: 'isolation', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Seated Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'McGill Crunch', muscle: 'Core', type: 'isolation', cue: 'Hands under the lower back · lift only the shoulders · spine stays neutral' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Incline Barbell Press', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Arnold Press', muscle: 'Shoulders', type: 'isolation', cue: 'Neutral spine · press to full lockout' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Overhead Rope Cable Extensions', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Romanian Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Front Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Banded Leg Extension', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Standing Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'McGill Crunch', muscle: 'Core', type: 'isolation', cue: 'Hands under the lower back · lift only the shoulders · spine stays neutral' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Incline Cable Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Bent Over Dumbbell Lateral', muscle: 'Rear Delts', type: 'secondary', cue: 'Hinge forward · elbows high · squeeze the rear delts' },
        { name: 'Chin-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Concentration Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
  ],
  2: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Braced T-Bar Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pullover Machine', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Machine Tricep Press-Down', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Preacher Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Machine Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Rack Deadlift', muscle: 'Hamstrings', type: 'isolation', cue: 'Pins at knee height · overload the lockout' },
        { name: 'Reverse Hyperextensions', muscle: 'Glutes', type: 'isolation', cue: 'Hips over the pad · squeeze the glutes at the top' },
        { name: 'Leg Press Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'McGill Crunch', muscle: 'Core', type: 'isolation', cue: 'Hands under the lower back · lift only the shoulders · spine stays neutral' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Incline Barbell Press', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Push Jerk', muscle: 'Shoulders', type: 'isolation', cue: 'Dip and drive · punch under the bar · lock out overhead' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Overhead Rope Cable Extensions', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Trap Bar Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Leg Press', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Banded Leg Extension', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Seated Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Pallof Press', muscle: 'Core', type: 'isolation', cue: 'Resist the rotation · press straight out and hold' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Flat Cable Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Cable Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Front Lateral Raise', muscle: 'Side Delts', type: 'secondary', cue: 'Lead with the elbow · no momentum' },
        { name: 'Neutral Grip Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Machine Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
  ],
  3: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Braced T-Bar Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Cable Pullover', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Concentration Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Front Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Rack Deadlift', muscle: 'Hamstrings', type: 'isolation', cue: 'Pins at knee height · overload the lockout' },
        { name: 'Reverse Hyperextensions', muscle: 'Glutes', type: 'isolation', cue: 'Hips over the pad · squeeze the glutes at the top' },
        { name: 'Leg Press Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Bird Dogs', muscle: 'Core', type: 'isolation', cue: 'Opposite arm and leg · hips square · no rotation' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Close Grip Bench Press', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Arnold Press', muscle: 'Shoulders', type: 'isolation', cue: 'Neutral spine · press to full lockout' },
        { name: 'Dumbbell Preacher Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Overhead Rope Cable Extensions', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Romanian Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Front Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Banded Leg Extension', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Leg Press Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Pallof Press', muscle: 'Core', type: 'isolation', cue: 'Resist the rotation · press straight out and hold' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Decline Dumbbell Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Reverse Pec Deck Fly', muscle: 'Rear Delts', type: 'secondary', cue: 'Elbows high · squeeze at the end range' },
        { name: 'Supinated Grip Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Concentration Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Machine Tricep Press-Down', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
  ],
  4: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Pendlay Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Single Arm Cable Press-Down', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Dumbbell Preacher Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Belt Squat', muscle: 'Quads', type: 'secondary', cue: 'Load hangs from the hips · zero spinal compression' },
        { name: 'Hyperextensions', muscle: 'Hamstrings', type: 'isolation', cue: 'Round to neutral · glutes and hamstrings, no spinal load' },
        { name: 'Dumbbell Leg Curl', muscle: 'Hamstrings', type: 'isolation', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Leg Press Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Deadbugs', muscle: 'Core', type: 'isolation', cue: 'Lower back pinned to the floor · slow opposite arm and leg' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Decline Machine Press', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Push Jerk', muscle: 'Shoulders', type: 'isolation', cue: 'Dip and drive · punch under the bar · lock out overhead' },
        { name: 'Machine Preacher Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Rope Press-Down', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Deadlift from Boxes', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on boxes · shortened range · heavier top-end pull' },
        { name: 'Safety Bar Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Donkey Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Bird Dogs', muscle: 'Core', type: 'isolation', cue: 'Opposite arm and leg · hips square · no rotation' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Incline Dumbbell Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Prone Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Reverse Pec Deck Fly', muscle: 'Rear Delts', type: 'secondary', cue: 'Elbows high · squeeze at the end range' },
        { name: 'Cable Pullover', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
      ],
    },
  ],
  5: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Chin-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Single Arm Cable Press-Down', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Belt Squat', muscle: 'Quads', type: 'secondary', cue: 'Load hangs from the hips · zero spinal compression' },
        { name: 'Romanian Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Dumbbell Leg Curl', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Leg Press Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Bird Dogs', muscle: 'Core', type: 'isolation', cue: 'Opposite arm and leg · hips square · no rotation' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Flat Machine Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Smith Machine Shoulder Press', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Overhead Rope Cable Extensions', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Deadlift from Boxes', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on boxes · shortened range · heavier top-end pull' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Leg Press Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'McGill Crunch', muscle: 'Core', type: 'isolation', cue: 'Hands under the lower back · lift only the shoulders · spine stays neutral' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Decline Cable Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Front Lateral Raise', muscle: 'Side Delts', type: 'secondary', cue: 'Lead with the elbow · no momentum' },
        { name: 'Pullover Machine', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Kickback', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
  ],
  6: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Pendlay Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Close Grip Lat Pull-Down', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Kickback', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Machine Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Safety Bar Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Deadlift from Boxes', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on boxes · shortened range · heavier top-end pull' },
        { name: 'Reverse Hyperextensions', muscle: 'Glutes', type: 'secondary', cue: 'Hips over the pad · squeeze the glutes at the top' },
        { name: 'Standing Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Bird Dogs', muscle: 'Core', type: 'isolation', cue: 'Opposite arm and leg · hips square · no rotation' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Floor Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Arnold Press', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Cable Tricep Kickback', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Deadlift from Boxes', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on boxes · shortened range · heavier top-end pull' },
        { name: 'Leg Press', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Banded Leg Extension', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Seated Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'McGill Crunch', muscle: 'Core', type: 'isolation', cue: 'Hands under the lower back · lift only the shoulders · spine stays neutral' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Decline Dumbbell Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Cable Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Reverse Pec Deck Fly', muscle: 'Rear Delts', type: 'secondary', cue: 'Elbows high · squeeze at the end range' },
        { name: 'Neutral Grip Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Preacher Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
  ],
  7: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Cable Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Wide Grip Lat Pull-Down', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Cable Tricep Kickback', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Machine Preacher Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Machine Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Deadlift from Boxes', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on boxes · shortened range · heavier top-end pull' },
        { name: 'Single Leg Curl', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Leg Press Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Deadbugs', muscle: 'Core', type: 'isolation', cue: 'Lower back pinned to the floor · slow opposite arm and leg' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Decline Dumbbell Chest Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Seated Dumbbell Press', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Hyperextensions', muscle: 'Hamstrings', type: 'secondary', cue: 'Round to neutral · glutes and hamstrings, no spinal load' },
        { name: 'Front Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Machine Leg Extension', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Standing Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Deadbugs', muscle: 'Core', type: 'isolation', cue: 'Lower back pinned to the floor · slow opposite arm and leg' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Incline Cable Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Prone Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Front Lateral Raise', muscle: 'Side Delts', type: 'secondary', cue: 'Lead with the elbow · no momentum' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Preacher Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'V-Bar Cable Press-Down', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
  ],
  8: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Barbell Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Chin-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Kickback', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Preacher Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Machine Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Dumbbell Romanian Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Dumbbell Leg Curl', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Standing Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Bird Dogs', muscle: 'Core', type: 'isolation', cue: 'Opposite arm and leg · hips square · no rotation' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Decline Barbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Push Jerk', muscle: 'Shoulders', type: 'secondary', cue: 'Dip and drive · punch under the bar · lock out overhead' },
        { name: 'Dumbbell Preacher Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Kickback', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Rack Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Pins at knee height · overload the lockout' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Machine Leg Extension', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Seated Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Bird Dogs', muscle: 'Core', type: 'isolation', cue: 'Opposite arm and leg · hips square · no rotation' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Pec Deck Machine', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Machine Lateral Raise', muscle: 'Side Delts', type: 'secondary', cue: 'Lead with the elbow · no momentum' },
        { name: 'Chin-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
      ],
    },
  ],
  9: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Cable Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Machine Tricep Press-Down', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Dumbbell Preacher Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Belt Squat', muscle: 'Quads', type: 'secondary', cue: 'Load hangs from the hips · zero spinal compression' },
        { name: 'Stiff Legged Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Prone Leg Curl', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Donkey Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'McGill Crunch', muscle: 'Core', type: 'isolation', cue: 'Hands under the lower back · lift only the shoulders · spine stays neutral' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Floor Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Standing Military Press', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Dumbbell Preacher Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Kickback', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Deadlift from Boxes', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on boxes · shortened range · heavier top-end pull' },
        { name: 'Front Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Banded Leg Extension', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Donkey Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Deadbugs', muscle: 'Core', type: 'isolation', cue: 'Lower back pinned to the floor · slow opposite arm and leg' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Flat Cable Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Pendlay Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Front Lateral Raise', muscle: 'Side Delts', type: 'secondary', cue: 'Lead with the elbow · no momentum' },
        { name: 'Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Rope Press-Down', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
  ],
  10: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Cable Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pullover Machine', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'V-Bar Cable Press-Down', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Concentration Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Leg Press', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Romanian Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Prone Leg Curl', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Standing Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Pallof Press', muscle: 'Core', type: 'isolation', cue: 'Resist the rotation · press straight out and hold' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Incline Dumbbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Smith Machine Shoulder Press', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Overhead Rope Cable Extensions', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Dumbbell Romanian Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Front Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Machine Leg Extension', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Seated Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Deadbugs', muscle: 'Core', type: 'isolation', cue: 'Lower back pinned to the floor · slow opposite arm and leg' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Flat Cable Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Lateral Raise', muscle: 'Side Delts', type: 'secondary', cue: 'Lead with the elbow · no momentum' },
        { name: 'Neutral Grip Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Concentration Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Overhead Rope Cable Extensions', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
  ],
  11: [
    {
      key: 'A', name: 'Upper — Press', shortName: 'Upper — Press', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Overhead Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Barbell Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'Machine Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Hyperextensions', muscle: 'Hamstrings', type: 'secondary', cue: 'Round to neutral · glutes and hamstrings, no spinal load' },
        { name: 'Glute Ham Raise', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Seated Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Bird Dogs', muscle: 'Core', type: 'isolation', cue: 'Opposite arm and leg · hips square · no rotation' },
      ],
    },
    {
      key: 'C', name: 'Upper — Pull', shortName: 'Upper — Pull', day: 'Day 3', focus: 'Back · Chest · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Decline Dumbbell Chest Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Seated Dumbbell Press', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to full lockout' },
        { name: 'Preacher Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Rope Press-Down', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Dumbbell Romanian Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Machine Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Donkey Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'McGill Crunch', muscle: 'Core', type: 'isolation', cue: 'Hands under the lower back · lift only the shoulders · spine stays neutral' },
      ],
    },
    {
      key: 'E', name: 'Upper — Volume & BFR', shortName: 'Upper — Volume & BFR', day: 'Day 5', focus: 'Chest · Back · Delts · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-70 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Incline Dumbbell Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Pendlay Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Upright Row', muscle: 'Side Delts', type: 'secondary', cue: 'Lead with the elbow · no momentum' },
        { name: 'Wide Grip Lat Pull-Down', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
      ],
    },
  ],
  12: [
    {
      key: 'A', name: 'Upper — Press — Testing', shortName: 'Upper — Press · Test', day: 'Day 1', focus: 'Chest · Shoulders · Back · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~25-35 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Decline Cable Fly', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Machine Leg Extension', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Dumbbell Prone Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
      ],
    },
    {
      key: 'B', name: 'Lower A — Testing', shortName: 'Lower A · Test', day: 'Day 2', focus: 'Quads · Hamstrings · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~25-35 min', restTimes: '2.5-3 min main lifts · 90 sec accessories · 45 sec BFR',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Hyperextensions', muscle: 'Hamstrings', type: 'secondary', cue: 'Round to neutral · glutes and hamstrings, no spinal load' },
        { name: 'Machine Pull-Down', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Preacher Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'V-Bar Cable Press-Down', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
        { name: 'McGill Crunch', muscle: 'Core', type: 'isolation', cue: 'Hands under the lower back · lift only the shoulders · spine stays neutral' },
      ],
    },
  ],
}

export function bbUpperWorkouts(week: number): Workout[] {
  return WEEK_WORKOUTS[Math.max(1, Math.min(12, week))] ?? WEEK_WORKOUTS[1]
}

const BFR_NOTE  = 'Blood-flow restriction set. Cuffs on, roughly a quarter of your normal working weight: 30 reps, then 15, then 15, with about 30 seconds between. It should burn hard - that is the point. These sets never count toward your 1RM.'
const TEST_NOTE = 'Max test: work up in small jumps until you find the heaviest clean set you can manage, then log it.'

export function bbUpperPrescription(dayKey: string, exerciseName: string, week: number): Prescription | null {
  const cell = SCHEDULE[dayKey]?.[exerciseName]?.[Math.max(1, Math.min(12, week))]
  if (!cell) return null
  const [sets, reps, rir, repsLabel, flag, section] = cell

  if (flag === 'BFR') {
    return { sets, reps, rir: 0, pct: BFR_PCT, repsLabel, protocol: 'bfr', noOneRm: true, testNote: BFR_NOTE }
  }
  if (section === 'REP TESTING') {
    return { sets, reps, rir: 0, pct: 1.0, repsLabel: `Work up to a ${reps}RM`, testMode: 'onerm', testNote: TEST_NOTE }
  }
  return { sets, reps, rir, pct: rtfPercent(reps, rir), repsLabel }
}

export function getBbUpperWeekConfig(week: number, _dayType?: DayType): WeekConfig {
  const isTest = week === 12
  return {
    sets:  { primary: 4, secondary: 3, isolation: 3 },
    reps:  { primary: '8', secondary: '12', isolation: '15' },
    rir: isTest ? 0 : 1,
    phase: isTest ? 'Week 12 - Max Testing' : `Accumulation - Week ${week} of 11`,
    isDeload: false,
    note: isTest
      ? 'Test week. Two days only: work up to true maxes on the main lifts, then light accessory work. This is what the last eleven weeks were for.'
      : 'Exercise selection rotates weekly by design. Main lifts stay heavy at RIR 2; accessories chase volume. Where a set is marked BFR, use cuffs and roughly a quarter of your normal load.',
    percentages: { primary: rtfPercent(8, 2), secondary: rtfPercent(12, 1), isolation: rtfPercent(15, 1) },
  }
}

export const BB_UPPER_PROGRAM: Program = {
  id:            BB_UPPER_ID,
  name:          'Bodybuilder Upper Body Focus - 5-Day',
  shortName:     'BB Upper',
  author:        'Biolayne Workout Builder',
  description:   'Twelve weeks on a five-day split weighted toward upper-body development, with two lower-body days holding strength. Heavy main lifts open every session at RIR 2, followed by higher-rep accessory work, and the fifth day finishes with blood-flow-restriction arm work. Exercise selection rotates every week. Week 12 is a dedicated test week: two days of true max attempts on the main lifts.',
  focus:         'Hypertrophy · Upper Body',
  daysPerWeek:   5,
  totalWeeks:    12,
  split:         'Upper / Lower · 5-Day',
  workouts:      WEEK_WORKOUTS[1],
  getWeekConfig: getBbUpperWeekConfig,
}
