import type { Program, WeekConfig, DayType, Workout } from '@/types'
import { rtfPercent, type Prescription } from './phatCustom'

// ═══════════════════════════════════════════════════════════════════════
// Garage Gains: Hypertrophy — 4-Day
//
// Transcribed from the Garage Gains Workout Builder export (workout
// 321180), twelve weekly PDFs. Exercise selection rotates almost
// completely week to week — 90 distinct movements across the block — so
// workouts are indexed per week rather than per phase.
//
// The programme is built for a home/garage setup: barbell, dumbbells,
// bands and bodyweight, with almost no machine work. Several movements
// are deliberately equipment-light substitutes for machines (band
// abductions, partner-assisted calf raises, sissy squats).
//
// Focus lifts wave across the block — sets climb while reps and RIR
// fall (2x8 @ RIR3 in week 1 through to 5x5 near failure by week 11) —
// while accessory work stays in the 10-20 rep range. Where the source
// lists no RIR the set is taken to failure, stored as RIR 0.
//
// Source gives no loads and no rest intervals; %1RM uses the
// reps-to-failure model and rest follows a hypertrophy profile — the
// app's interpretation, not the source's.
// ═══════════════════════════════════════════════════════════════════════

export const GARAGE_GAINS_ID = 'garage-gains-4day'

/** [dayKey][exercise][week] -> [sets, midReps, rir, repsLabel, section]. */
const SCHEDULE: Record<string, Record<string, Record<number, [number, number, number, string, string]>>> = {
  A: {
    'Bench Press': { 1:[2,8,3,'8','FOCUS LIFTS'], 2:[3,8,3,'8','FOCUS LIFTS'], 3:[4,8,2,'8','FOCUS LIFTS'], 5:[3,6,3,'6','FOCUS LIFTS'], 6:[4,6,2,'6','FOCUS LIFTS'], 8:[5,6,0,'6','FOCUS LIFTS'], 10:[4,5,1,'5','FOCUS LIFTS'], 11:[5,5,1,'5','FOCUS LIFTS'] },
    'Pull-Up': { 1:[2,8,3,'8','FOCUS LIFTS'], 4:[4,8,0,'8','FOCUS LIFTS'] },
    'Spoto Press': { 1:[2,10,2,'10','ACCESSORY WORK'], 5:[2,10,2,'10','ACCESSORY WORK'], 7:[3,10,1,'10','ACCESSORY WORK'] },
    'Flat Dumbbell Fly': { 1:[2,15,2,'15','ACCESSORY WORK'], 2:[2,15,1,'15','ACCESSORY WORK'], 3:[2,15,2,'15','ACCESSORY WORK'], 4:[4,15,2,'15','ACCESSORY WORK'], 5:[2,15,2,'15','ACCESSORY WORK'], 6:[2,15,1,'15','ACCESSORY WORK'], 7:[3,15,2,'15','ACCESSORY WORK'], 8:[2,15,2,'15','ACCESSORY WORK'], 9:[2,15,2,'15','ACCESSORY WORK'], 10:[3,15,2,'15','ACCESSORY WORK'], 11:[3,15,1,'15','ACCESSORY WORK'], 12:[3,15,1,'15','ACCESSORY WORK'] },
    'T-Bar Row': { 1:[3,10,2,'10','ACCESSORY WORK'], 5:[3,6,3,'6','FOCUS LIFTS'], 6:[4,6,2,'6','FOCUS LIFTS'], 8:[4,6,1,'6','FOCUS LIFTS'], 9:[3,10,2,'10','ACCESSORY WORK'], 11:[4,10,1,'10','ACCESSORY WORK'] },
    'Band Assisted Pull-Up': { 1:[3,10,2,'10','ACCESSORY WORK'], 6:[3,10,1,'10','ACCESSORY WORK'], 11:[4,10,1,'10','ACCESSORY WORK'], 12:[4,10,1,'10','ACCESSORY WORK'] },
    'Seated Dumbbell Lateral Raise': { 1:[2,20,2,'20','ACCESSORY WORK'], 7:[3,15,2,'15','ACCESSORY WORK'], 9:[2,15,2,'15','ACCESSORY WORK'], 11:[4,15,2,'15','ACCESSORY WORK'] },
    'Standing Alternating Dumbbell Curl': { 1:[3,20,2,'20','ACCESSORY WORK'], 12:[5,15,0,'15','ACCESSORY WORK'] },
    'Dumbbell Skull Crusher': { 1:[3,20,2,'20','ACCESSORY WORK'], 6:[3,20,2,'20','ACCESSORY WORK'], 7:[4,20,2,'20','ACCESSORY WORK'] },
    'Chin-Up': { 2:[3,8,3,'8','FOCUS LIFTS'], 3:[4,8,2,'8','FOCUS LIFTS'] },
    'Weighted Push-Up': { 2:[2,10,2,'10','ACCESSORY WORK'], 6:[2,10,1,'10','ACCESSORY WORK'], 12:[3,10,1,'10','ACCESSORY WORK'] },
    'Dumbbell Row': { 2:[3,10,2,'10','ACCESSORY WORK'], 4:[5,15,2,'15','ACCESSORY WORK'], 5:[3,10,2,'10','ACCESSORY WORK'], 6:[3,10,1,'10','ACCESSORY WORK'], 7:[4,10,1,'10','ACCESSORY WORK'], 10:[3,10,2,'10','ACCESSORY WORK'] },
    'Dumbbell Pullover': { 2:[3,10,1,'10','ACCESSORY WORK'], 3:[3,10,1,'10','ACCESSORY WORK'], 4:[4,15,2,'15','ACCESSORY WORK'], 5:[3,10,2,'10','ACCESSORY WORK'], 8:[3,15,2,'15','ACCESSORY WORK'], 9:[3,10,2,'10','ACCESSORY WORK'], 10:[3,10,2,'10','ACCESSORY WORK'] },
    'Front Lateral Raise': { 2:[3,15,1,'15','ACCESSORY WORK'], 6:[2,15,2,'15','ACCESSORY WORK'] },
    'Hammer Curl': { 2:[3,20,1,'20','ACCESSORY WORK'] },
    'Seated Overhead Dumbbell Tricep Extension': { 2:[3,20,1,'20','ACCESSORY WORK'], 4:[4,20,2,'20','ACCESSORY WORK'], 8:[3,20,2,'20','ACCESSORY WORK'] },
    'Flat Dumbbell Press': { 3:[2,10,1,'10','ACCESSORY WORK'], 4:[4,8,0,'8','FOCUS LIFTS'], 7:[4,6,1,'6','FOCUS LIFTS'], 8:[2,10,1,'10','ACCESSORY WORK'], 9:[3,5,2,'5','FOCUS LIFTS'], 11:[2,10,1,'10','ACCESSORY WORK'], 12:[5,5,0,'5','FOCUS LIFTS'] },
    'Landmine Row': { 3:[3,10,1,'10','ACCESSORY WORK'], 12:[5,10,1,'10','ACCESSORY WORK'] },
    'Incline Dumbbell Reverse Fly': { 3:[3,15,2,'15','ACCESSORY WORK'], 12:[5,15,1,'15','ACCESSORY WORK'] },
    'Cross Body Hammer Curl': { 3:[3,20,2,'20','ACCESSORY WORK'] },
    'EZ-Bar Skull Crusher': { 3:[3,20,2,'20','ACCESSORY WORK'], 5:[3,20,2,'20','ACCESSORY WORK'], 9:[3,15,2,'15','ACCESSORY WORK'] },
    'Close Grip Bench Press': { 4:[3,10,1,'10','ACCESSORY WORK'], 9:[2,10,2,'10','ACCESSORY WORK'], 10:[2,10,2,'10','ACCESSORY WORK'] },
    'Seated Dumbbell Front Raise': { 4:[4,15,2,'15','ACCESSORY WORK'], 10:[3,15,2,'15','ACCESSORY WORK'] },
    'Dumbbell Curl': { 4:[5,20,2,'20','ACCESSORY WORK'], 11:[5,15,2,'15','ACCESSORY WORK'] },
    'Lateral Raise': { 5:[2,20,2,'20','ACCESSORY WORK'], 8:[2,15,2,'15','ACCESSORY WORK'] },
    'Concentration Curl': { 5:[3,20,2,'20','ACCESSORY WORK'], 8:[3,20,2,'20','ACCESSORY WORK'] },
    'Dumbbell Spider Curl': { 6:[3,20,2,'20','ACCESSORY WORK'], 10:[4,15,2,'15','ACCESSORY WORK'] },
    'Barbell Row': { 7:[4,6,1,'6','FOCUS LIFTS'] },
    'Partner Assisted Pull-Up': { 7:[4,10,1,'10','ACCESSORY WORK'] },
    'Cambered Bar Curl': { 7:[4,20,2,'20','ACCESSORY WORK'], 9:[3,15,2,'15','ACCESSORY WORK'] },
    'Dumbbell Prone Row': { 8:[3,15,2,'15','ACCESSORY WORK'] },
    'Pendlay Row': { 10:[4,5,1,'5','FOCUS LIFTS'], 11:[4,5,1,'5','FOCUS LIFTS'], 12:[5,5,1,'5','FOCUS LIFTS'] },
    'Seated Single Arm Dumbbell Tricep Extension': { 10:[4,15,2,'15','ACCESSORY WORK'], 11:[5,15,2,'15','ACCESSORY WORK'], 12:[5,15,0,'15','ACCESSORY WORK'] },
  },
  B: {
    'Back Squat': { 1:[2,8,3,'8','FOCUS LIFTS'], 3:[4,8,2,'8','FOCUS LIFTS'], 5:[3,6,3,'6','FOCUS LIFTS'], 7:[4,6,1,'6','FOCUS LIFTS'], 12:[5,5,0,'5','FOCUS LIFTS'] },
    'Deadlift': { 1:[2,8,3,'8','FOCUS LIFTS'], 3:[4,8,2,'8','FOCUS LIFTS'], 5:[3,6,3,'6','FOCUS LIFTS'] },
    'Sissy Squat': { 1:[2,10,2,'10','ACCESSORY WORK'], 4:[3,10,0,'10','ACCESSORY WORK'], 7:[3,10,1,'10','ACCESSORY WORK'] },
    'Front Foot Elevated Split Squat': { 1:[3,15,2,'15','ACCESSORY WORK'], 8:[3,15,2,'15','ACCESSORY WORK'], 11:[4,15,2,'15','ACCESSORY WORK'] },
    'Block Pull Deadlift': { 1:[2,10,2,'10','ACCESSORY WORK'], 2:[2,10,2,'10','ACCESSORY WORK'], 3:[2,10,1,'10','ACCESSORY WORK'], 10:[3,10,2,'10','ACCESSORY WORK'] },
    'Single Leg Dumbbell Hip Thrust': { 1:[3,10,2,'10','ACCESSORY WORK'] },
    'Single Leg Dumbbell Calf Raise': { 1:[3,12,2,'12','ACCESSORY WORK'], 2:[3,12,1,'12','ACCESSORY WORK'], 3:[3,12,1,'12','ACCESSORY WORK'], 6:[3,12,1,'12','ACCESSORY WORK'], 7:[4,12,1,'12','ACCESSORY WORK'], 10:[4,12,2,'12','ACCESSORY WORK'], 12:[5,12,0,'12','ACCESSORY WORK'] },
    'Plank': { 1:[3,12,0,'12','CORE WORK'] },
    'Front Squat': { 2:[3,8,3,'8','FOCUS LIFTS'], 6:[4,6,2,'6','FOCUS LIFTS'], 9:[3,5,2,'5','FOCUS LIFTS'] },
    'Halting Deadlifts': { 2:[3,8,3,'8','FOCUS LIFTS'], 6:[4,6,2,'6','FOCUS LIFTS'], 7:[4,6,1,'6','FOCUS LIFTS'], 10:[4,5,1,'5','FOCUS LIFTS'] },
    'High Bar Back Squat': { 2:[2,10,2,'10','ACCESSORY WORK'], 8:[5,6,0,'6','FOCUS LIFTS'], 9:[2,10,2,'10','ACCESSORY WORK'], 10:[3,10,2,'10','ACCESSORY WORK'], 11:[3,10,1,'10','ACCESSORY WORK'] },
    'Pistol Squat': { 2:[3,15,1,'15','ACCESSORY WORK'], 7:[4,15,2,'15','ACCESSORY WORK'] },
    'Banded Donkey Kick': { 2:[3,10,2,'10','ACCESSORY WORK'], 4:[4,10,1,'10','ACCESSORY WORK'] },
    'Swiss Ball Crunch': { 2:[3,12,0,'12','CORE WORK'], 3:[3,12,0,'12','CORE WORK'] },
    'Goblet Squat': { 3:[2,10,1,'10','ACCESSORY WORK'], 6:[2,10,1,'10','ACCESSORY WORK'], 8:[2,10,1,'10','ACCESSORY WORK'], 12:[3,10,1,'10','ACCESSORY WORK'] },
    'Lunge': { 3:[3,15,2,'15','ACCESSORY WORK'], 6:[3,15,2,'15','ACCESSORY WORK'], 9:[3,15,2,'15','ACCESSORY WORK'], 10:[3,15,2,'15','ACCESSORY WORK'], 12:[4,15,0,'15','ACCESSORY WORK'] },
    'Standing Banded Leg Abduction': { 3:[3,10,1,'10','ACCESSORY WORK'] },
    'Pause Squat': { 4:[4,8,1,'8','FOCUS LIFTS'], 10:[4,5,1,'5','FOCUS LIFTS'], 11:[5,5,1,'5','FOCUS LIFTS'] },
    'Sumo Stance Deadlift': { 4:[4,8,2,'8','FOCUS LIFTS'], 8:[4,6,2,'6','FOCUS LIFTS'], 9:[3,5,2,'5','FOCUS LIFTS'], 11:[4,5,1,'5','FOCUS LIFTS'], 12:[5,5,2,'5','FOCUS LIFTS'] },
    'Split Squat': { 4:[4,15,2,'15','ACCESSORY WORK'], 5:[3,15,2,'15','ACCESSORY WORK'] },
    'Stiff Legged Deadlift': { 4:[3,8,1,'8','ACCESSORY WORK'] },
    'Standing Dumbbell Calf Raise': { 4:[5,12,1,'12','ACCESSORY WORK'], 5:[3,12,2,'12','ACCESSORY WORK'], 8:[3,12,1,'12','ACCESSORY WORK'], 11:[5,12,1,'12','ACCESSORY WORK'] },
    'Banded Kneeling Crunch': { 4:[5,12,0,'12','CORE WORK'], 12:[5,15,0,'15','CORE WORK'] },
    'Dead Squat To Pins': { 5:[2,10,2,'10','ACCESSORY WORK'] },
    'Dumbbell Romanian Deadlift': { 5:[2,10,2,'10','ACCESSORY WORK'] },
    'Bird Dogs': { 5:[3,20,0,'20','CORE WORK'] },
    'B-Stance RDL': { 6:[2,10,1,'10','ACCESSORY WORK'], 11:[4,10,1,'10','ACCESSORY WORK'] },
    'Hanging Leg Raise': { 6:[3,20,0,'20','CORE WORK'] },
    'Romanian Deadlift': { 7:[3,10,1,'10','ACCESSORY WORK'] },
    'Russian Twist': { 7:[4,20,0,'20','CORE WORK'] },
    'Rack Deadlift': { 8:[2,15,2,'15','ACCESSORY WORK'] },
    'Side Bends': { 8:[4,20,0,'20','CORE WORK'] },
    'Good Morning From Pins': { 9:[2,10,2,'10','ACCESSORY WORK'] },
    'Standing Barbell Calf Raise': { 9:[3,12,2,'12','ACCESSORY WORK'] },
    'Deadbugs': { 9:[3,15,0,'15','CORE WORK'] },
    'Mountain Climbers': { 10:[3,15,0,'15','CORE WORK'] },
    'Reverse Crunch': { 11:[4,15,0,'15','CORE WORK'] },
    'Weighted RDL': { 12:[4,10,1,'10','ACCESSORY WORK'] },
  },
  C: {
    'Standing Military Press': { 1:[2,8,3,'8','FOCUS LIFTS'], 2:[3,8,3,'8','FOCUS LIFTS'], 8:[5,6,0,'6','FOCUS LIFTS'] },
    'Pull-Up': { 1:[2,8,3,'8','FOCUS LIFTS'], 3:[4,8,2,'8','FOCUS LIFTS'], 4:[4,8,1,'8','FOCUS LIFTS'], 5:[3,6,3,'6','FOCUS LIFTS'], 6:[3,6,2,'6','FOCUS LIFTS'], 9:[3,5,2,'5','FOCUS LIFTS'], 10:[4,5,1,'5','FOCUS LIFTS'], 11:[4,5,1,'5','FOCUS LIFTS'] },
    'Weighted Push-Up': { 1:[3,8,2,'8','ACCESSORY WORK'] },
    'Landmine Row': { 1:[3,15,2,'15','ACCESSORY WORK'], 7:[4,15,2,'15','ACCESSORY WORK'], 12:[4,15,2,'15','ACCESSORY WORK'] },
    'Partner Assisted Pull-Up': { 1:[3,15,2,'15','ACCESSORY WORK'], 11:[3,15,2,'15','ACCESSORY WORK'] },
    'Kneeling Single Arm Landmine Presses': { 1:[3,10,2,'10','ACCESSORY WORK'], 4:[5,8,1,'8','ACCESSORY WORK'], 9:[3,10,2,'10','ACCESSORY WORK'], 10:[3,10,2,'10','ACCESSORY WORK'], 11:[3,10,1,'10','ACCESSORY WORK'], 12:[3,10,1,'10','ACCESSORY WORK'] },
    'Cambered Bar Curl': { 1:[3,12,2,'12','ACCESSORY WORK'] },
    'Seated Overhead Dumbbell Tricep Extension': { 1:[3,12,2,'12','ACCESSORY WORK'], 5:[3,12,2,'12','ACCESSORY WORK'], 12:[5,10,0,'10','ACCESSORY WORK'] },
    'Chin-Up': { 2:[3,8,3,'8','FOCUS LIFTS'], 7:[4,6,1,'6','FOCUS LIFTS'], 8:[4,6,0,'6','FOCUS LIFTS'], 12:[5,5,0,'5','FOCUS LIFTS'] },
    'Flat Dumbbell Press': { 2:[3,8,2,'8','ACCESSORY WORK'], 6:[3,8,1,'8','ACCESSORY WORK'], 7:[4,8,1,'8','ACCESSORY WORK'], 9:[3,8,2,'8','ACCESSORY WORK'], 11:[4,8,1,'8','ACCESSORY WORK'] },
    'T-Bar Row': { 2:[3,15,1,'15','ACCESSORY WORK'], 5:[3,15,2,'15','ACCESSORY WORK'], 9:[3,15,2,'15','ACCESSORY WORK'] },
    'Arnold Press': { 2:[3,10,2,'10','ACCESSORY WORK'], 3:[3,8,1,'8','ACCESSORY WORK'], 6:[3,10,1,'10','ACCESSORY WORK'], 8:[4,15,1,'15','ACCESSORY WORK'] },
    'Kneeling Scrape the Rack Press': { 2:[3,8,2,'8','ACCESSORY WORK'], 3:[3,10,1,'10','ACCESSORY WORK'], 5:[3,10,2,'10','ACCESSORY WORK'], 7:[4,10,1,'10','ACCESSORY WORK'] },
    'Dumbbell Curl': { 2:[3,12,1,'12','ACCESSORY WORK'], 4:[5,12,1,'12','ACCESSORY WORK'], 5:[3,12,2,'12','ACCESSORY WORK'], 7:[5,12,1,'12','ACCESSORY WORK'] },
    'EZ-Bar Skull Crusher': { 2:[3,12,1,'12','ACCESSORY WORK'], 3:[3,12,1,'12','ACCESSORY WORK'], 9:[3,10,2,'10','ACCESSORY WORK'] },
    'Seated Dumbbell Press': { 3:[4,8,2,'8','FOCUS LIFTS'], 4:[4,8,0,'8','FOCUS LIFTS'], 7:[4,6,1,'6','FOCUS LIFTS'] },
    'JM Press': { 3:[3,8,1,'8','ACCESSORY WORK'] },
    'Dumbbell Row': { 3:[3,15,2,'15','ACCESSORY WORK'], 4:[5,15,2,'15','ACCESSORY WORK'], 6:[3,15,2,'15','ACCESSORY WORK'], 8:[3,15,1,'15','ACCESSORY WORK'], 10:[3,15,2,'15','ACCESSORY WORK'] },
    'Dumbbell Spider Curl': { 3:[3,12,1,'12','ACCESSORY WORK'] },
    'Close Grip Bench Press': { 4:[5,8,1,'8','ACCESSORY WORK'] },
    'Dumbbell Skull Crusher': { 4:[5,12,1,'12','ACCESSORY WORK'], 7:[5,12,1,'12','ACCESSORY WORK'], 10:[4,10,2,'10','ACCESSORY WORK'], 11:[5,10,1,'10','ACCESSORY WORK'] },
    'Seated Military Press': { 5:[3,6,3,'6','FOCUS LIFTS'], 6:[4,6,2,'6','FOCUS LIFTS'], 9:[3,5,2,'5','FOCUS LIFTS'] },
    'Bench Press': { 5:[3,8,2,'8','ACCESSORY WORK'], 8:[3,8,1,'8','ACCESSORY WORK'], 10:[3,8,2,'8','ACCESSORY WORK'], 12:[5,8,2,'8','ACCESSORY WORK'] },
    'Band Assisted Pull-Up': { 5:[3,15,2,'15','ACCESSORY WORK'], 6:[3,15,2,'15','ACCESSORY WORK'], 9:[3,15,2,'15','ACCESSORY WORK'], 10:[4,15,2,'15','ACCESSORY WORK'], 12:[4,15,2,'15','ACCESSORY WORK'] },
    'Seated Dumbbell Curl': { 6:[3,12,1,'12','ACCESSORY WORK'], 9:[3,10,2,'10','ACCESSORY WORK'], 12:[5,10,0,'10','ACCESSORY WORK'] },
    'Seated Single Arm Dumbbell Tricep Extension': { 6:[3,12,1,'12','ACCESSORY WORK'], 8:[5,12,0,'12','ACCESSORY WORK'] },
    'Dumbbell Pullover': { 7:[4,15,2,'15','ACCESSORY WORK'], 8:[3,15,1,'15','ACCESSORY WORK'] },
    'Standing Alternating Dumbbell Curl': { 8:[5,12,0,'12','ACCESSORY WORK'] },
    'Standing Dumbbell Shoulder Press': { 10:[4,5,1,'5','FOCUS LIFTS'], 11:[5,5,1,'5','FOCUS LIFTS'], 12:[5,5,0,'5','FOCUS LIFTS'] },
    'Concentration Curl': { 10:[4,10,2,'10','ACCESSORY WORK'] },
    'Dumbbell Prone Row': { 11:[3,15,2,'15','ACCESSORY WORK'] },
    'Cross Body Hammer Curl': { 11:[5,10,1,'10','ACCESSORY WORK'] },
  },
  D: {
    'Sumo Stance Deadlift': { 1:[2,8,3,'8','FOCUS LIFTS'], 3:[4,8,2,'8','FOCUS LIFTS'], 12:[5,5,0,'5','FOCUS LIFTS'] },
    'Dead Squat To Pins': { 1:[2,10,3,'10','FOCUS LIFTS'], 3:[4,10,2,'10','FOCUS LIFTS'], 5:[3,15,2,'15','ACCESSORY WORK'], 6:[3,15,2,'15','ACCESSORY WORK'], 7:[4,6,1,'6','FOCUS LIFTS'], 8:[4,6,2,'6','FOCUS LIFTS'] },
    'Front Squat': { 1:[3,15,2,'15','ACCESSORY WORK'], 4:[4,15,2,'15','FOCUS LIFTS'], 10:[4,10,1,'10','FOCUS LIFTS'], 11:[4,15,1,'15','FOCUS LIFTS'], 12:[5,8,2,'8','FOCUS LIFTS'] },
    'Pistol Squat': { 1:[3,15,2,'15','ACCESSORY WORK'], 4:[4,15,1,'15','ACCESSORY WORK'], 6:[3,15,2,'15','ACCESSORY WORK'] },
    'Single Leg RDL': { 1:[3,20,2,'20','ACCESSORY WORK'] },
    'Single Leg Dumbbell Calf Raise': { 1:[3,20,2,'20','ACCESSORY WORK'], 2:[3,20,1,'20','ACCESSORY WORK'], 3:[3,20,2,'20','ACCESSORY WORK'], 11:[5,15,1,'15','ACCESSORY WORK'], 12:[5,15,0,'15','ACCESSORY WORK'] },
    'Russian Twist': { 1:[3,20,0,'20','CORE WORK'], 8:[4,12,0,'12','CORE WORK'] },
    'Halting Deadlifts': { 2:[3,8,3,'8','FOCUS LIFTS'], 6:[4,6,2,'6','FOCUS LIFTS'] },
    'High Bar Back Squat': { 2:[3,10,3,'10','FOCUS LIFTS'], 6:[4,6,2,'6','FOCUS LIFTS'], 9:[3,15,2,'15','ACCESSORY WORK'] },
    'Goblet Squat': { 2:[3,15,1,'15','ACCESSORY WORK'], 4:[4,15,1,'15','ACCESSORY WORK'], 7:[4,15,2,'15','ACCESSORY WORK'], 8:[3,15,2,'15','ACCESSORY WORK'], 10:[4,10,2,'10','ACCESSORY WORK'], 11:[4,15,2,'15','ACCESSORY WORK'] },
    'Split Squat': { 2:[3,15,2,'15','ACCESSORY WORK'], 3:[3,15,2,'15','ACCESSORY WORK'], 7:[4,15,2,'15','ACCESSORY WORK'] },
    'Banded Glute Bridge': { 2:[3,20,1,'20','ACCESSORY WORK'], 11:[5,15,2,'15','ACCESSORY WORK'] },
    'Decline Leg Lower': { 2:[3,20,0,'20','CORE WORK'], 4:[4,20,0,'20','CORE WORK'], 5:[3,12,0,'12','CORE WORK'], 10:[4,10,0,'10','CORE WORK'] },
    'Sissy Squat': { 3:[3,15,2,'15','ACCESSORY WORK'], 5:[3,6,3,'6','FOCUS LIFTS'], 9:[3,8,2,'8','FOCUS LIFTS'], 12:[3,15,2,'15','ACCESSORY WORK'] },
    'Banded Lateral Walk': { 3:[3,20,2,'20','ACCESSORY WORK'], 12:[5,15,2,'15','ACCESSORY WORK'] },
    'Hanging Leg Raise': { 3:[3,20,0,'20','CORE WORK'] },
    'Deadlift': { 4:[4,8,0,'8','FOCUS LIFTS'], 7:[4,6,1,'6','FOCUS LIFTS'], 9:[3,5,2,'5','FOCUS LIFTS'], 10:[4,5,1,'5','FOCUS LIFTS'], 11:[5,5,1,'5','FOCUS LIFTS'] },
    'Frog Pump': { 4:[5,15,1,'15','ACCESSORY WORK'], 10:[4,15,2,'15','ACCESSORY WORK'] },
    'Standing Dumbbell Calf Raise': { 4:[5,20,2,'20','ACCESSORY WORK'], 9:[3,15,2,'15','ACCESSORY WORK'], 10:[4,15,2,'15','ACCESSORY WORK'] },
    'Deficit Deadlifts': { 5:[3,6,3,'6','FOCUS LIFTS'], 8:[5,6,0,'6','FOCUS LIFTS'] },
    'Front Foot Elevated Split Squat': { 5:[3,15,2,'15','ACCESSORY WORK'], 8:[3,15,2,'15','ACCESSORY WORK'] },
    'Rack Deadlift': { 5:[3,20,2,'20','ACCESSORY WORK'] },
    'Partner Assisted Donkey Calf Raise': { 5:[3,20,2,'20','ACCESSORY WORK'], 6:[3,20,2,'20','ACCESSORY WORK'], 8:[3,20,2,'20','ACCESSORY WORK'] },
    'Banded Hip Thrust': { 6:[3,20,2,'20','ACCESSORY WORK'] },
    'Side Bends': { 6:[3,12,0,'12','CORE WORK'], 12:[5,10,0,'10','CORE WORK'] },
    'Barbell Hip Thrust': { 7:[5,20,2,'20','ACCESSORY WORK'], 8:[4,15,2,'15','ACCESSORY WORK'], 9:[3,15,2,'15','ACCESSORY WORK'] },
    'Standing Barbell Calf Raise': { 7:[4,20,2,'20','ACCESSORY WORK'] },
    'Plank': { 7:[4,12,0,'12','CORE WORK'] },
    'Single Leg Landmine RDL': { 9:[3,15,2,'15','ACCESSORY WORK'], 10:[4,15,2,'15','ACCESSORY WORK'], 11:[4,15,2,'15','ACCESSORY WORK'], 12:[4,15,0,'15','ACCESSORY WORK'] },
    'Bird Dogs': { 9:[3,10,0,'10','CORE WORK'] },
    'Mountain Climbers': { 11:[4,10,0,'10','CORE WORK'] },
  },
}

const WEEK_WORKOUTS: Record<number, Workout[]> = {
  1: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Spoto Press', muscle: 'Chest', type: 'secondary', cue: 'Pause the bar an inch off the chest · no bounce · builds control out of the hole' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Band Assisted Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Band under the knee · reduce band thickness as you get stronger' },
        { name: 'Seated Dumbbell Lateral Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Standing Alternating Dumbbell Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'secondary', cue: 'Knees travel forward · deep quad stretch · slow and controlled' },
        { name: 'Front Foot Elevated Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Front foot on a plate · deeper stretch on the front leg' },
        { name: 'Block Pull Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on blocks · shortened range · overload the top half of the pull' },
        { name: 'Single Leg Dumbbell Hip Thrust', muscle: 'Glutes', type: 'secondary', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Plank', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Standing Military Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Weighted Push-Up', muscle: 'Chest', type: 'secondary', cue: 'Plate on the upper back · full range · body stays in one line' },
        { name: 'Landmine Row', muscle: 'Back', type: 'isolation', cue: 'Chest over the bar · row to the hip · one arm or two' },
        { name: 'Partner Assisted Pull-Up', muscle: 'Back', type: 'isolation', cue: 'Partner assists at the shins · only as much help as you need' },
        { name: 'Kneeling Single Arm Landmine Presses', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Overhead Dumbbell Tricep Extension', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Sumo Stance Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Dead Squat To Pins', muscle: 'Quads', type: 'primary', cue: 'Start from a dead stop on the pins · no stretch reflex · pure concentric strength' },
        { name: 'Front Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Pistol Squat', muscle: 'Quads', type: 'isolation', cue: 'Full single-leg squat · hold a counterweight out front if you need balance' },
        { name: 'Single Leg RDL', muscle: 'Hamstrings', type: 'isolation', cue: 'Hips square · reach the free leg back as a counterweight' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Russian Twist', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
  ],
  2: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Chin-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Weighted Push-Up', muscle: 'Chest', type: 'secondary', cue: 'Plate on the upper back · full range · body stays in one line' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Front Lateral Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Hammer Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Overhead Dumbbell Tricep Extension', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Front Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Halting Deadlifts', muscle: 'Hamstrings', type: 'primary', cue: 'Pause just below the knee on the way up · builds position under load' },
        { name: 'High Bar Back Squat', muscle: 'Quads', type: 'secondary', cue: 'Bar on the traps · upright torso · more quad than a low-bar squat' },
        { name: 'Pistol Squat', muscle: 'Quads', type: 'isolation', cue: 'Full single-leg squat · hold a counterweight out front if you need balance' },
        { name: 'Block Pull Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on blocks · shortened range · overload the top half of the pull' },
        { name: 'Banded Donkey Kick', muscle: 'Glutes', type: 'secondary', cue: 'Drive the heel back and up · no lower-back arch' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Swiss Ball Crunch', muscle: 'Core', type: 'isolation', cue: 'Ball under the lower back · full extension then crunch · bigger range than the floor' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Standing Military Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Chin-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Arnold Press', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Kneeling Scrape the Rack Press', muscle: 'Shoulders', type: 'secondary', cue: 'Press up and INTO the uprights · huge upper-back and delt tension' },
        { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Halting Deadlifts', muscle: 'Hamstrings', type: 'primary', cue: 'Pause just below the knee on the way up · builds position under load' },
        { name: 'High Bar Back Squat', muscle: 'Quads', type: 'primary', cue: 'Bar on the traps · upright torso · more quad than a low-bar squat' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Banded Glute Bridge', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Decline Leg Lower', muscle: 'Core', type: 'isolation', cue: 'Lower back pinned · lower the legs only as far as you can hold position' },
      ],
    },
  ],
  3: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Chin-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Landmine Row', muscle: 'Back', type: 'secondary', cue: 'Chest over the bar · row to the hip · one arm or two' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Incline Dumbbell Reverse Fly', muscle: 'Rear Delts', type: 'isolation', cue: 'Chest on an incline bench · elbows high · squeeze the rear delts' },
        { name: 'Cross Body Hammer Curl', muscle: 'Biceps', type: 'isolation', cue: 'Neutral grip across the body to the opposite shoulder · brachialis emphasis' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Lunge', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Block Pull Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on blocks · shortened range · overload the top half of the pull' },
        { name: 'Standing Banded Leg Abduction', muscle: 'Glutes', type: 'secondary', cue: 'Band at the ankle · sweep the leg out and slightly back' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Swiss Ball Crunch', muscle: 'Core', type: 'isolation', cue: 'Ball under the lower back · full extension then crunch · bigger range than the floor' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Seated Dumbbell Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'JM Press', muscle: 'Triceps', type: 'secondary', cue: 'Half skull-crusher, half close-grip press · elbows forward · heavy triceps work' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Kneeling Scrape the Rack Press', muscle: 'Shoulders', type: 'secondary', cue: 'Press up and INTO the uprights · huge upper-back and delt tension' },
        { name: 'Arnold Press', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Dumbbell Spider Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Sumo Stance Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Dead Squat To Pins', muscle: 'Quads', type: 'primary', cue: 'Start from a dead stop on the pins · no stretch reflex · pure concentric strength' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'isolation', cue: 'Knees travel forward · deep quad stretch · slow and controlled' },
        { name: 'Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Banded Lateral Walk', muscle: 'Glutes', type: 'isolation', cue: 'Band above the knees · stay low · small controlled steps' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Hanging Leg Raise', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
  ],
  4: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Close Grip Bench Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Seated Dumbbell Front Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Overhead Dumbbell Tricep Extension', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Pause Squat', muscle: 'Quads', type: 'primary', cue: 'Two-count pause at the bottom · no bounce out of the hole' },
        { name: 'Sumo Stance Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'secondary', cue: 'Knees travel forward · deep quad stretch · slow and controlled' },
        { name: 'Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Stiff Legged Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Banded Donkey Kick', muscle: 'Glutes', type: 'secondary', cue: 'Drive the heel back and up · no lower-back arch' },
        { name: 'Standing Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Banded Kneeling Crunch', muscle: 'Core', type: 'isolation', cue: 'Band overhead · crunch the ribcage to the pelvis · pull with the abs' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Seated Dumbbell Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Close Grip Bench Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Kneeling Single Arm Landmine Presses', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Front Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Pistol Squat', muscle: 'Quads', type: 'isolation', cue: 'Full single-leg squat · hold a counterweight out front if you need balance' },
        { name: 'Frog Pump', muscle: 'Glutes', type: 'isolation', cue: 'Soles together, knees out · pure glute squeeze at the top · high reps' },
        { name: 'Standing Dumbbell Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Decline Leg Lower', muscle: 'Core', type: 'isolation', cue: 'Lower back pinned · lower the legs only as far as you can hold position' },
      ],
    },
  ],
  5: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Spoto Press', muscle: 'Chest', type: 'secondary', cue: 'Pause the bar an inch off the chest · no bounce · builds control out of the hole' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Lateral Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Concentration Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Dead Squat To Pins', muscle: 'Quads', type: 'secondary', cue: 'Start from a dead stop on the pins · no stretch reflex · pure concentric strength' },
        { name: 'Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Dumbbell Romanian Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Standing Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Bird Dogs', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Seated Military Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Bench Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Band Assisted Pull-Up', muscle: 'Back', type: 'isolation', cue: 'Band under the knee · reduce band thickness as you get stronger' },
        { name: 'Kneeling Scrape the Rack Press', muscle: 'Shoulders', type: 'secondary', cue: 'Press up and INTO the uprights · huge upper-back and delt tension' },
        { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Overhead Dumbbell Tricep Extension', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Deficit Deadlifts', muscle: 'Hamstrings', type: 'primary', cue: 'Stand on a plate · extra range · brutal off the floor' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'primary', cue: 'Knees travel forward · deep quad stretch · slow and controlled' },
        { name: 'Dead Squat To Pins', muscle: 'Quads', type: 'isolation', cue: 'Start from a dead stop on the pins · no stretch reflex · pure concentric strength' },
        { name: 'Front Foot Elevated Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Front foot on a plate · deeper stretch on the front leg' },
        { name: 'Rack Deadlift', muscle: 'Hamstrings', type: 'isolation', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Partner Assisted Donkey Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Hinge at the hips, partner on the back · deep stretch under load' },
        { name: 'Decline Leg Lower', muscle: 'Core', type: 'isolation', cue: 'Lower back pinned · lower the legs only as far as you can hold position' },
      ],
    },
  ],
  6: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Weighted Push-Up', muscle: 'Chest', type: 'secondary', cue: 'Plate on the upper back · full range · body stays in one line' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Band Assisted Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Band under the knee · reduce band thickness as you get stronger' },
        { name: 'Front Lateral Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Dumbbell Spider Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Front Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Halting Deadlifts', muscle: 'Hamstrings', type: 'primary', cue: 'Pause just below the knee on the way up · builds position under load' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Lunge', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'B-Stance RDL', muscle: 'Hamstrings', type: 'secondary', cue: 'Back toe as a kickstand only · nearly all the load on the working leg' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Hanging Leg Raise', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Seated Military Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Band Assisted Pull-Up', muscle: 'Back', type: 'isolation', cue: 'Band under the knee · reduce band thickness as you get stronger' },
        { name: 'Arnold Press', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Seated Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Single Arm Dumbbell Tricep Extension', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Halting Deadlifts', muscle: 'Hamstrings', type: 'primary', cue: 'Pause just below the knee on the way up · builds position under load' },
        { name: 'High Bar Back Squat', muscle: 'Quads', type: 'primary', cue: 'Bar on the traps · upright torso · more quad than a low-bar squat' },
        { name: 'Dead Squat To Pins', muscle: 'Quads', type: 'isolation', cue: 'Start from a dead stop on the pins · no stretch reflex · pure concentric strength' },
        { name: 'Pistol Squat', muscle: 'Quads', type: 'isolation', cue: 'Full single-leg squat · hold a counterweight out front if you need balance' },
        { name: 'Banded Hip Thrust', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Partner Assisted Donkey Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Hinge at the hips, partner on the back · deep stretch under load' },
        { name: 'Side Bends', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
  ],
  7: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Barbell Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Spoto Press', muscle: 'Chest', type: 'secondary', cue: 'Pause the bar an inch off the chest · no bounce · builds control out of the hole' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Partner Assisted Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Partner assists at the shins · only as much help as you need' },
        { name: 'Seated Dumbbell Lateral Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Halting Deadlifts', muscle: 'Hamstrings', type: 'primary', cue: 'Pause just below the knee on the way up · builds position under load' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'secondary', cue: 'Knees travel forward · deep quad stretch · slow and controlled' },
        { name: 'Pistol Squat', muscle: 'Quads', type: 'isolation', cue: 'Full single-leg squat · hold a counterweight out front if you need balance' },
        { name: 'Romanian Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Russian Twist', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Seated Dumbbell Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Chin-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Landmine Row', muscle: 'Back', type: 'isolation', cue: 'Chest over the bar · row to the hip · one arm or two' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Kneeling Scrape the Rack Press', muscle: 'Shoulders', type: 'secondary', cue: 'Press up and INTO the uprights · huge upper-back and delt tension' },
        { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Dead Squat To Pins', muscle: 'Quads', type: 'primary', cue: 'Start from a dead stop on the pins · no stretch reflex · pure concentric strength' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Barbell Hip Thrust', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Standing Barbell Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Plank', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
  ],
  8: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Prone Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Lateral Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Concentration Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Overhead Dumbbell Tricep Extension', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'High Bar Back Squat', muscle: 'Quads', type: 'primary', cue: 'Bar on the traps · upright torso · more quad than a low-bar squat' },
        { name: 'Sumo Stance Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Front Foot Elevated Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Front foot on a plate · deeper stretch on the front leg' },
        { name: 'Rack Deadlift', muscle: 'Hamstrings', type: 'isolation', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Standing Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Side Bends', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Standing Military Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Chin-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Bench Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Arnold Press', muscle: 'Shoulders', type: 'isolation', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Standing Alternating Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Single Arm Dumbbell Tricep Extension', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Deficit Deadlifts', muscle: 'Hamstrings', type: 'primary', cue: 'Stand on a plate · extra range · brutal off the floor' },
        { name: 'Dead Squat To Pins', muscle: 'Quads', type: 'primary', cue: 'Start from a dead stop on the pins · no stretch reflex · pure concentric strength' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Front Foot Elevated Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Front foot on a plate · deeper stretch on the front leg' },
        { name: 'Barbell Hip Thrust', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Partner Assisted Donkey Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Hinge at the hips, partner on the back · deep stretch under load' },
        { name: 'Russian Twist', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
  ],
  9: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Close Grip Bench Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Seated Dumbbell Lateral Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Cambered Bar Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Front Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Sumo Stance Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'High Bar Back Squat', muscle: 'Quads', type: 'secondary', cue: 'Bar on the traps · upright torso · more quad than a low-bar squat' },
        { name: 'Lunge', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Good Morning From Pins', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar on pins at the bottom · dead-stop hinge · start light, this is humbling' },
        { name: 'Standing Barbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Deadbugs', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Seated Military Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Band Assisted Pull-Up', muscle: 'Back', type: 'isolation', cue: 'Band under the knee · reduce band thickness as you get stronger' },
        { name: 'Kneeling Single Arm Landmine Presses', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Seated Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'EZ-Bar Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'primary', cue: 'Knees travel forward · deep quad stretch · slow and controlled' },
        { name: 'High Bar Back Squat', muscle: 'Quads', type: 'isolation', cue: 'Bar on the traps · upright torso · more quad than a low-bar squat' },
        { name: 'Single Leg Landmine RDL', muscle: 'Hamstrings', type: 'isolation', cue: 'Landmine gives you an arc to follow · hips square, no rotation' },
        { name: 'Barbell Hip Thrust', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Standing Dumbbell Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Bird Dogs', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
  ],
  10: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Pendlay Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Close Grip Bench Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Dumbbell Pullover', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Seated Dumbbell Front Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Dumbbell Spider Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Single Arm Dumbbell Tricep Extension', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Pause Squat', muscle: 'Quads', type: 'primary', cue: 'Two-count pause at the bottom · no bounce out of the hole' },
        { name: 'Halting Deadlifts', muscle: 'Hamstrings', type: 'primary', cue: 'Pause just below the knee on the way up · builds position under load' },
        { name: 'High Bar Back Squat', muscle: 'Quads', type: 'secondary', cue: 'Bar on the traps · upright torso · more quad than a low-bar squat' },
        { name: 'Lunge', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Block Pull Deadlift', muscle: 'Hamstrings', type: 'secondary', cue: 'Bar raised on blocks · shortened range · overload the top half of the pull' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Mountain Climbers', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Standing Dumbbell Shoulder Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Bench Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Band Assisted Pull-Up', muscle: 'Back', type: 'isolation', cue: 'Band under the knee · reduce band thickness as you get stronger' },
        { name: 'Kneeling Single Arm Landmine Presses', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Concentration Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Front Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Single Leg Landmine RDL', muscle: 'Hamstrings', type: 'isolation', cue: 'Landmine gives you an arc to follow · hips square, no rotation' },
        { name: 'Frog Pump', muscle: 'Glutes', type: 'isolation', cue: 'Soles together, knees out · pure glute squeeze at the top · high reps' },
        { name: 'Standing Dumbbell Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Decline Leg Lower', muscle: 'Core', type: 'isolation', cue: 'Lower back pinned · lower the legs only as far as you can hold position' },
      ],
    },
  ],
  11: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Bench Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Pendlay Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'T-Bar Row', muscle: 'Back', type: 'secondary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Band Assisted Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Band under the knee · reduce band thickness as you get stronger' },
        { name: 'Seated Dumbbell Lateral Raise', muscle: 'Side Delts', type: 'isolation', cue: 'Lead with the elbow · no momentum' },
        { name: 'Dumbbell Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Single Arm Dumbbell Tricep Extension', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Pause Squat', muscle: 'Quads', type: 'primary', cue: 'Two-count pause at the bottom · no bounce out of the hole' },
        { name: 'Sumo Stance Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'High Bar Back Squat', muscle: 'Quads', type: 'secondary', cue: 'Bar on the traps · upright torso · more quad than a low-bar squat' },
        { name: 'Front Foot Elevated Split Squat', muscle: 'Glutes', type: 'isolation', cue: 'Front foot on a plate · deeper stretch on the front leg' },
        { name: 'B-Stance RDL', muscle: 'Hamstrings', type: 'secondary', cue: 'Back toe as a kickstand only · nearly all the load on the working leg' },
        { name: 'Standing Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Reverse Crunch', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Standing Dumbbell Shoulder Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Pull-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Dumbbell Prone Row', muscle: 'Back', type: 'isolation', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Partner Assisted Pull-Up', muscle: 'Back', type: 'isolation', cue: 'Partner assists at the shins · only as much help as you need' },
        { name: 'Kneeling Single Arm Landmine Presses', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Cross Body Hammer Curl', muscle: 'Biceps', type: 'secondary', cue: 'Neutral grip across the body to the opposite shoulder · brachialis emphasis' },
        { name: 'Dumbbell Skull Crusher', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Front Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Single Leg Landmine RDL', muscle: 'Hamstrings', type: 'isolation', cue: 'Landmine gives you an arc to follow · hips square, no rotation' },
        { name: 'Banded Glute Bridge', muscle: 'Glutes', type: 'isolation', cue: 'Drive through the heels · squeeze at lockout' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Mountain Climbers', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
  ],
  12: [
    {
      key: 'A', name: 'Upper A', shortName: 'Upper A', day: 'Day 1', focus: 'Chest · Back · Shoulders · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Flat Dumbbell Press', muscle: 'Chest', type: 'primary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Pendlay Row', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Weighted Push-Up', muscle: 'Chest', type: 'secondary', cue: 'Plate on the upper back · full range · body stays in one line' },
        { name: 'Flat Dumbbell Fly', muscle: 'Chest', type: 'isolation', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Landmine Row', muscle: 'Back', type: 'secondary', cue: 'Chest over the bar · row to the hip · one arm or two' },
        { name: 'Band Assisted Pull-Up', muscle: 'Back', type: 'secondary', cue: 'Band under the knee · reduce band thickness as you get stronger' },
        { name: 'Incline Dumbbell Reverse Fly', muscle: 'Rear Delts', type: 'isolation', cue: 'Chest on an incline bench · elbows high · squeeze the rear delts' },
        { name: 'Standing Alternating Dumbbell Curl', muscle: 'Biceps', type: 'isolation', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Single Arm Dumbbell Tricep Extension', muscle: 'Triceps', type: 'isolation', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'B', name: 'Lower A', shortName: 'Lower A', day: 'Day 2', focus: 'Quads · Hamstrings · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Back Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Sumo Stance Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Goblet Squat', muscle: 'Quads', type: 'secondary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Lunge', muscle: 'Quads', type: 'isolation', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Weighted RDL', muscle: 'Hamstrings', type: 'secondary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'secondary', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Banded Kneeling Crunch', muscle: 'Core', type: 'isolation', cue: 'Band overhead · crunch the ribcage to the pelvis · pull with the abs' },
      ],
    },
    {
      key: 'C', name: 'Upper B', shortName: 'Upper B', day: 'Day 3', focus: 'Shoulders · Back · Chest · Arms',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Standing Dumbbell Shoulder Press', muscle: 'Shoulders', type: 'primary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Chin-Up', muscle: 'Back', type: 'primary', cue: 'Full stretch · drive the elbows back · squeeze' },
        { name: 'Bench Press', muscle: 'Chest', type: 'secondary', cue: 'Full stretch at the bottom · controlled tempo' },
        { name: 'Landmine Row', muscle: 'Back', type: 'isolation', cue: 'Chest over the bar · row to the hip · one arm or two' },
        { name: 'Band Assisted Pull-Up', muscle: 'Back', type: 'isolation', cue: 'Band under the knee · reduce band thickness as you get stronger' },
        { name: 'Kneeling Single Arm Landmine Presses', muscle: 'Shoulders', type: 'secondary', cue: 'Neutral spine · press to a full lockout' },
        { name: 'Seated Dumbbell Curl', muscle: 'Biceps', type: 'secondary', cue: 'Elbows fixed · full extension at the bottom' },
        { name: 'Seated Overhead Dumbbell Tricep Extension', muscle: 'Triceps', type: 'secondary', cue: 'Elbows pinned · full lockout' },
      ],
    },
    {
      key: 'D', name: 'Lower B', shortName: 'Lower B', day: 'Day 4', focus: 'Hamstrings · Quads · Glutes · Calves · Core',
      dayType: 'hypertrophy' as DayType, isRest: false,
      duration: '~45-65 min', restTimes: '2.5-3 min focus lifts · 90 sec accessories · 60 sec core',
      exercises: [
        { name: 'Sumo Stance Deadlift', muscle: 'Hamstrings', type: 'primary', cue: 'Hips back · slow eccentric · full stretch' },
        { name: 'Front Squat', muscle: 'Quads', type: 'primary', cue: 'Controlled depth · drive through the mid-foot' },
        { name: 'Sissy Squat', muscle: 'Quads', type: 'isolation', cue: 'Knees travel forward · deep quad stretch · slow and controlled' },
        { name: 'Single Leg Landmine RDL', muscle: 'Hamstrings', type: 'isolation', cue: 'Landmine gives you an arc to follow · hips square, no rotation' },
        { name: 'Banded Lateral Walk', muscle: 'Glutes', type: 'isolation', cue: 'Band above the knees · stay low · small controlled steps' },
        { name: 'Single Leg Dumbbell Calf Raise', muscle: 'Calves', type: 'isolation', cue: 'Full stretch at the bottom · pause at the top' },
        { name: 'Side Bends', muscle: 'Core', type: 'isolation', cue: 'Brace hard · control the tempo' },
      ],
    },
  ],
}

export function garageGainsWorkouts(week: number): Workout[] {
  return WEEK_WORKOUTS[Math.max(1, Math.min(12, week))] ?? WEEK_WORKOUTS[1]
}

export function garageGainsPrescription(dayKey: string, exerciseName: string, week: number): Prescription | null {
  const cell = SCHEDULE[dayKey]?.[exerciseName]?.[Math.max(1, Math.min(12, week))]
  if (!cell) return null
  const [sets, reps, rir, repsLabel] = cell
  return { sets, reps, rir, pct: rtfPercent(reps, rir), repsLabel }
}

export function getGarageGainsWeekConfig(week: number, _dayType?: DayType): WeekConfig {
  // Representative shape taken from the day-1 focus lift of each week.
  const focus = SCHEDULE.A ? Object.values(SCHEDULE.A).map(r => r[week]).find(Boolean) : undefined
  const sets  = focus?.[0] ?? 3
  const reps  = focus?.[3] ?? '8'
  const rir   = focus?.[2] ?? 2
  const block = week <= 4 ? 1 : week <= 8 ? 2 : 3
  return {
    sets:  { primary: sets, secondary: 3, isolation: 3 },
    reps:  { primary: String(reps), secondary: '10-12', isolation: '15-20' },
    rir,
    phase: `Block ${block} — Week ${week} of 12`,
    isDeload: false,
    note: 'Exercise selection rotates almost every week by design — the variety is the programme. Focus lifts wave heavier across the block while accessories hold the rep ranges. Where no RIR is listed, take the set to failure.',
    percentages: {
      primary:   rtfPercent(typeof reps === 'string' ? parseInt(reps) || 8 : 8, rir),
      secondary: rtfPercent(11, 1),
      isolation: rtfPercent(17, 2),
    },
  }
}

export const GARAGE_GAINS_PROGRAM: Program = {
  id:            GARAGE_GAINS_ID,
  name:          'Garage Gains: Hypertrophy — 4-Day',
  shortName:     'Garage Gains',
  author:        'Biolayne Workout Builder',
  description:   'Twelve weeks, four days a week, built for a home or garage gym — barbell, dumbbells, bands and bodyweight, with almost no machine work. Upper and lower days alternate, each opening with two heavy focus lifts before a run of accessory work. Exercise selection rotates almost completely week to week across ninety movements, and the focus lifts wave heavier through the block: sets climb while reps and reps-in-reserve fall, from 2x8 at three in reserve up to 5x5 near failure.',
  focus:         'Hypertrophy · Home Gym',
  daysPerWeek:   4,
  totalWeeks:    12,
  split:         'Upper / Lower · 4-Day',
  workouts:      WEEK_WORKOUTS[1],
  getWeekConfig: getGarageGainsWeekConfig,
}
